### ISSUE TITLE
Linux porting

### ISSUE THREAD

**Issue by vipenzo** [exyte/Macaw#101]
Is there some plan/activity to port this to linux ?
If not can you provide some guidelines for anyone willing to try ?

**Comment by ystrot** [comment]
Hi Vincenzo!

Macaw was built around Apple's Cocoa which unfortunately doesn't exist for Linux. It would be great to have all the same API around another rendering engine, but this will be huge amount of work. If you want to try then you can start with examination of Macaw rendering system: https://github.com/exyte/Macaw/tree/master/Source/render. The idea would be replace all UIKit-dependent code with some Linux-based system (for example GTK).

**Comment by vipenzo** [comment]
Thanks Yuri, I will take a look.
I saw some project around claiming to build a swift CoreGraphics for Linux, I don't know if they are mature enough though.
