### ISSUE TITLE
OSX Support

### ISSUE THREAD

**Issue by wildthink** [exyte/Macaw#107]
I noticed that OS X was mentioned in the notes but not currently supported. Is it still on the roadmap?
It looks like the code is factored with this in mind. How much effort do think would be involved?

**Comment by ystrot** [comment]
Hi Jason,

This task doesn't look too complicated. Need to unify work with UIFont, UIImage and fix some OS X specific parts (like coordinate system). Unfortunately, it's not on our roadmap (at least in the nearest couple of months). However we would be glad to review your work if you would like to try.
