### ISSUE TITLE
SVGView svgNode property made open var instead of fileprivate var

### ISSUE THREAD

**Issue by deathByLiche** [exyte/Macaw#108]
It would be nice if the svgNode property on the SVGView was open, not fileprivate. Currently there is no way to dynamically change the svg on the SVGView without changing the filename. This prevents a previously parsed svg node from being set on the SVGView with the proper content mode without creating a new instance of SVGView.

**Comment by ystrot** [comment]
Not sure I understand your use case. `svgNode` actually an internal property which might be removed in future. SVGView should be used to display SVG files from the storyboard. If you want to change SVG dynamically, you can always use MacawView and SVGParser directly.

**Comment by deathByLiche** [comment]
The use case I have is dynamically changing the svg (using SVGParser to get a new root node) while also getting the benefit of the content mode resizing provided in the SVGView class. 

MacawView provides the ability to change the svg root node, but doesn't allow for content mode scaling. I'd like the ability to set a new root node on the SVGView, just like you can set a new filename and have it re-render for the correct content mode.

**Comment by ystrot** [comment]
Sorry for late response. I got your point, but still thinking that using SVGView with dynamic content might be too complicated. A better solution would be to add content mode to MacawView. And I think we can implement it in one of upcoming releases.

For now you can just copy&paste SVGView implementation to your code and customize it as you like.

**Comment by deathByLiche** [comment]
Awesome that's good to hear!

**Comment by ystrot** [comment]
`MacawView` now supports content mode, so closing this issue.
