### ISSUE TITLE
MacawView never gets deinited 

### ISSUE THREAD

**Issue by deathByLiche** [exyte/Macaw#109]
It seems that any MacawView that gets instantiated, never gets released, even if it is removed from the view hierarchy and set to nil.

 I believe that the RenderContext and NodesMap are holding strong references to the view, as well as maybe the AnimationCache.

**Comment by vhailor13** [comment]
Hello @deathByLiche ,
Thanks for reporting this issue. Fixed in latest **master** commits:
7e8d619f5482eaf4554d2b50924559a93654f9ec
7966950c505f6ae8fbd0b05a46081fbc9d8aaeaa

**Comment by deathByLiche** [comment]
Thanks for the quick fix! 

As I was poking around more yesterday, it also looks like Macaw never releases some of it resources. Every time you use SVGParser to parse an svg, it increases the memory footprint, which never seems to go away. I even tried parsing an svg and immediately throwing away the returned node and it still increased the apps memory.

**Comment by vhailor13** [comment]
@deathByLiche Just fixed nasty leak 32a5b21415ca2dd1d8744654d9d7b76a5aa7bca4 Now nodes should be released properly. Thanks for report!
