### ISSUE TITLE
Swift 3 Warnings

### ISSUE THREAD

**Issue by jewilhel** [exyte/Macaw#110]
When I imported this framework. I noticed about 8 warning messages in the framework that I believe are Swift 3 language change issues. Hopefully I can fix them and use the framework successfully.

**Comment by vhailor13** [comment]
Hello @jewilhel , can you specify warning messages please?

**Comment by agildehaus** [comment]
@vhailor13:  Basically two items.

M_PI is depreciated, use Double.pi or .pi

**Comment by jewilhel** [comment]
Yeah, the warnings seemed to be related to:
M_PI is depreciated, use Double.pi or .pi and I was able to get it working after fixing. Sorry for not being more specific about the warnings.

**Comment by vhailor13** [comment]
Fixed in **master** branch. Will be included next release.
