### ISSUE TITLE
SVGView ScaleAspectFit broken for non square SVG's

### ISSUE THREAD

**Issue by deathByLiche** [exyte/Macaw#111]
Svg's rendered in an SVGView using ScaleAspectFit are not scaled properly if the SVG is not approximately a square.

It looks like the svgNode.bounds() is returning a rect that is larger than the svg width and height, which then throws off the scaleAspectFit calculations. For example, an svg with a width of 320 and height of 700 (a tall rectangle) might have the svgNode.bounds() return a rect that is closer to a width of 700 and a height of 700 (a Square).

The algorithm seems to be correct as I commented out the two lines in the render method that calculates the svgWidth and svgHeight based on the node bounds, and replaced the values with the actual width and height of my test svg's and everything worked properly.

**Comment by ystrot** [comment]
Sorry for late response. A developer who was assigned to this issue is too busy on another project, so I'm reassigning this ticket. Could you please attach an SVG file with incorrect bounds calculation?

**Comment by deathByLiche** [comment]
Absolutely. 

This svg is 247 x 344 but the rect returned from it's bounds is ~ 312 x 343, thus throwing off the scaling calculations. If you hardcode the width and height to be 247 x 344 in the scaling algorithm, it scales properly.

[bodyMapCard.svg.zip](https://github.com/exyte/Macaw/files/993673/bodyMapCard.svg.zip)

**Comment by ystrot** [comment]
Thanks! Reproduced this issue.

**Comment by rmtmckenzie** [comment]
Any word on when this will be fixed? I've run into it in one of my projects. I _may_ have time next week to investigate myself if someone can point me in the right direction...

**Comment by ystrot** [comment]
Hi Morgan! Thanks for your readiness to help! However we just fixed this issue in the master. So you can try the latest version using:
```
pod 'Macaw', :git => 'https://github.com/exyte/Macaw.git'
```

**Comment by rmtmckenzie** [comment]
I'll give it a test, thanks!
