### ISSUE TITLE
Convert Node to SVG

### ISSUE THREAD

**Issue by mohammadrhemmati** [exyte/Macaw#112]
Is is possible to convert and save a root node as SVG?

**Comment by ystrot** [comment]
Unfortunately, it's not possible for now. However this task is not that big, so we'll try to schedule it to the one of upcoming releases.

**Comment by ystrot** [comment]
Done! You can use `SVGSerializer.serialize()` method to convert Node to SVG.

**Comment by mohammadrhemmati** [comment]
Thanks !
