### ISSUE TITLE
Scaling  MacawView is not affected by layer.anchorPoint

### ISSUE THREAD

**Issue by icanswiftabit** [exyte/Macaw#113]
Why is that? Is `node` have other anchorePoint?

**Comment by vhailor13** [comment]
Hello @bwdowikowski, MacawView's scene is not affected by layer's parameters. Scale transformation is implemented by applying transformation matrix to the scene.

**Comment by bwdowikowski** [comment]
Hi @vhailor13, do you think is it a worth adding feature?

**Comment by vhailor13** [comment]
Not really, you can manipulate scene directly using transformation matrix and adjust it for a special anchor point. Maybe the good solution will be to add a simple interface for such matrix generation.

**Comment by bwdowikowski** [comment]
A simple wrapper would be for such matrix would be nice.

**Comment by bwdowikowski** [comment]
@vhailor13 by writing 

> transformation matrix and adjust it for a special anchor point

you meant adjusting `dx` and `dy` in `scale` func or some other func?

**Comment by vhailor13** [comment]
You can use combination of existing methods: http://math.stackexchange.com/questions/5805/scaling-at-an-arbitrary-point-and-figuring-out-the-distance-from-origin
It should be looking something like:
`someNode.place = Transform
		.move(dx: -1.0 * anchorPoint.x, dy: -1.0 * anchorPoint.y)
		.scale(sx: scaleX, sy: scaleY),
		.move(dx: anchorPoint.x, dy: anchorPoint.y)`

**Comment by icanswiftabit** [comment]
I did try it but without luck.

My handle pinch looks like this
```
dynamic func handlePich(recognizer: UIPinchGestureRecognizer) {
    guard let view = recognizer.view as? SVGView else { return }
    let scale = Double(recognizer.scale)
    recognizer.scale = 1
    let anchor = recognizer.location(in: view)

    view.node.place = Transform
                    .move(dx: -1.0 * anchor.x.double, dy: -1.0 * anchor.y.double)
                    .scale(sx: scale, sy: scale)
                    .move(dx: anchor.x.double, dy: anchor.y.double)
}
```
![results](https://cloud.githubusercontent.com/assets/1766317/25026360/65baa27e-20a6-11e7-93a7-2fe17d1e55da.gif)

So I'm assuming that I should change `Transform` to `view.node.place` and final code should be

```
dynamic func handlePich(recognizer: UIPinchGestureRecognizer) {
    guard let view = recognizer.view as? SVGView else { return }
    let scale = Double(recognizer.scale)
    recognizer.scale = 1
    let anchor = recognizer.location(in: view)

    view.node.place = view.node.place
                    .move(dx: -1.0 * anchor.x.double, dy: -1.0 * anchor.y.double)
                    .scale(sx: scale, sy: scale)
                    .move(dx: anchor.x.double, dy: anchor.y.double)
}
```
![results](https://cloud.githubusercontent.com/assets/1766317/25026353/5e9afb56-20a6-11e7-9010-67c53b51d64d.gif)

But the results are still not as I expected. Am I doing it ok?

**Comment by vhailor13** [comment]
My bad, working solution is:
https://gist.github.com/vhailor13/080770c0c553cfba8951fbd6c40cbdc1

**Comment by icanswiftabit** [comment]
Uhh sorry  @vhailor13 for such late answer. That is working like a charm. Do you think this should be in the tutorial or better into separated method?
