### ISSUE TITLE
Animation with Polyline

### ISSUE THREAD

**Issue by charliefancelli** [exyte/Macaw#114]
Hi,

Is it possible to animate a `Polyline`? 

I just spent 2 hours without success.
I tried to make an easy opacity animation with a circle and it's works but with a Polyline there is not animation, only the first state and the final state. Did i missed something ?

```
...
let spider = Polyline(points: points).fill(with: Color.red)
spider.onTap{ _ in
    spider.opacityVar.animate(from: 0.0, to: 1.0, during: 1, delay: 0.0) //not animation
    circleExtern.opacityVar.animate(from: 0.0, to: 1.0, during: 1, delay: 0.0) //it's works
}
```

Thx

**Comment by vhailor13** [comment]
Hello @charliefancelli ,
Just fixed this bug in **master** branch. Upcoming release will contain this fix. Until then you can link master branch in Podfile:
`pod 'Macaw', git: 'https://github.com/exyte/Macaw.git'`

Thanks for report!

**Comment by charliefancelli** [comment]
hi @vhailor13 ,
Thanks for the fix (it's fix the scale too ^^ )
