### ISSUE TITLE
Touch Events on Text Nodes never fire

### ISSUE THREAD

**Issue by deathByLiche** [exyte/Macaw#115]
Touch events on Text nodes never seem to fire. They work fine on Group nodes and Shape nodes, but not Text nodes.

**Comment by vhailor13** [comment]
Hello @deathByLiche,
Just fixed this bug in **master** branch. Upcoming release will contain this fix. Until then you can link master branch in Podfile:
pod 'Macaw', git: 'https://github.com/exyte/Macaw.git'

**Comment by deathByLiche** [comment]
Awesome thanks!
