### ISSUE TITLE
Add shadow to Polyline

### ISSUE THREAD

**Issue by charliefancelli** [exyte/Macaw#116]
Hi,

Can we add a shadow to a `Polyline`?
I saw that the documention as to be added.

When i set 
```
let spider = Polyline(points: points).fill(with: redColor)
spider.opacity = 0.6
spider.effect = DropShadow(radius: 10, offset: Point(x: 2, y: 2), color: Color.rgba(r: 0, g: 0, b: 0, a: 0.6))
```
the polyline doesn't have any shadow.

Thanks ?

**Comment by ystrot** [comment]
Hi,

Unfortunately Shadow/Effects API is work in progress and doesn't work yet. It's not clear when it will be released, but I can let you know when it happens.

**Comment by charliefancelli** [comment]
hi @ystrot ,

Thanks for the reply, nice if the feature will be released in the futur.

**Comment by f3dm76** [comment]
On the master branch you can now drop the shadow like this

`yourShape.effect = Effect.dropShadow()`

<img width="87" alt="screen shot 2018-06-21 at 17 39 00" src="https://user-images.githubusercontent.com/9447630/41714286-0004cb4c-757a-11e8-980b-7e4bbd19434f.png">

**Comment by ystrot** [comment]
0.9.2 released, so closing this issue.
