### ISSUE TITLE
Add shape dynamically ?

### ISSUE THREAD

**Issue by charliefancelli** [exyte/Macaw#117]
Hi,

Is it possible to add shapes after set the group in `node` ?
```
self.node = Group(contents: items)
```
I would like to add new shape if user click on a button for exemple.

I tried do find an `add` or `insert` function without succeed.

Thanks,

**Comment by vhailor13** [comment]
Hello @charliefancelli ,
There are several options for this:
https://gist.github.com/vhailor13/7eeef557e7ffe743f75205d8b806662f

**Comment by charliefancelli** [comment]
thank, i did that but i was not sure if i was the good way.
