### ISSUE TITLE
Is it possible to change points of Polyline already added to Group?

### ISSUE THREAD

**Issue by ChechkovEugene** [exyte/Macaw#121]
Is it possible to change points of Polyline already added to Group? If i remove it from the group.contains or replace it with new Polilyne previous line is visible. Or maybe exists some redraw region redraw procedure for such cases?

**Comment by vhailor13** [comment]
Hello @ChechkovEugene , this issue sounds like redrawing logic bug. Can you provide us code with example?

**Comment by ChechkovEugene** [comment]
On tapping on element polyline to that element is creating. On the next tap previous line is removing . On the third tap first polyline(deleted on the second tap) and third are visible.
[macaw_test.zip](https://github.com/exyte/Macaw/files/987475/macaw_test.zip)

**Comment by ystrot** [comment]
Hi Eugene,

Thanks for reporting! This is really an Macaw rendering issue, will try to fix it ASAP.

**Comment by vhailor13** [comment]
Finally fixed this issue, you can try it using master branch: 
pod 'Macaw', :git => 'https://github.com/exyte/Macaw.git'

**Comment by ChechkovEugene** [comment]
Checked. Works like a clock! Thanks so much!
