### ISSUE TITLE
Issue Loading SVG

### ISSUE THREAD

**Issue by littlebearuk** [exyte/Macaw#122]
Hi,

I am creating SVG programatically:

 let vectorView = SVGView.init(frame: CGRect(x: 0, y: 0, width:50, height: 50))
            vectorView.backgroundColor = .red
            vectorView.fileName = "cameraIcon"
            vectorView.isUserInteractionEnabled = false

However no image is showing... Any ideas?

**Comment by littlebearuk** [comment]
Sorry.

Of course I also added: self.view.addSubview(vectorView)

**Comment by ystrot** [comment]
Your code looks correct, so you probably has an issue of loading your SVG file. To find it you can parse SVG manually and use `MacawView` to render it:
```Swift
let node = try! SVGParser.parse(path: "cameraIcon")
let vectorView = MacawView(node: node, frame: CGRect(x: 0, y: 0, width:50, height: 50))
vectorView.backgroundColor = .red
vectorView.isUserInteractionEnabled = false
self.view.addSubview(vectorView)
```
With this code you'll catch an runtime error in case of SVG loading problems. If it will be parsed correctly, but still nothing is showing then you can attach your SVG file and we'll check it's supported by Macaw.

**Comment by ystrot** [comment]
Closing this issue. Please let us know if you have any other questions/problems.
