### ISSUE TITLE
SVGView views should return an intrinsic content size and use height/width attributes

### ISSUE THREAD

**Issue by wiedem** [exyte/Macaw#126]
SVGView views currently don't have an intrinsic content size.
Furthermore SVGView (SVGParser) doesn't evaluate the [width](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/width) and [height](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/height) attributes of the SVG root element at all - those attributes could be used for the intrinsic content size.

Providing an intrinsic content size for the SVGView would allow a proper auto layout handling depending on the content and would provide a similar behavior to UIImageView.

**Comment by ystrot** [comment]
Thanks for reporting! We're going to make some work related to SVG parser in this milestone. Will take a look at this issue as well.

**Comment by pauarmada** [comment]
https://github.com/exyte/Macaw/pull/128

**Comment by pauarmada** [comment]
Hello, I created a PR for this: https://github.com/exyte/Macaw/pull/139
Would be great if it can be merged. Thanks!

**Comment by pauarmada** [comment]
Tagging @ystrot. Thanks!

**Comment by ystrot** [comment]
Closing this issue, because content layout supported now and available in the release version.
