### ISSUE TITLE
Allow any UIImage to be used with Image

### ISSUE THREAD

**Issue by sluramod** [exyte/Macaw#127]
At the moment the only option is to use named UIImage and no way to override this because `bounds() `function is internal and `uiImage` is private.

`override func bounds() -> Rect? {
...
uiImage = UIImage(named: src)
...`

**Comment by vhailor13** [comment]
Hello @sluramod ,
Just pushed [image bounds fix](https://github.com/exyte/Macaw/commit/a2b4a04821939ac81c8f250faa5b19c568ea26ea) to **master** branch. It also contains public constructor with UIImage argument. You can use it via
 pod 'Macaw', :git => 'https://github.com/exyte/Macaw.git'
Hope it helps!

**Comment by ystrot** [comment]
Hey @sluramod! I'm closing this issue. Feel free to reopen it or create another one if you have some other questions.
