### ISSUE TITLE
Export Settings

### ISSUE THREAD

**Issue by chriskilpin** [exyte/Macaw#130]
Hi Guys

I am having varying results exporting SVG files from Sketch / Illustrator. The main issues seem to be around alignment. Could I ask what are the recommended export settings are?

**Comment by ystrot** [comment]
Hi Christopher,

Could you please attach SVG which have alignment issues? It's probably a rendering issue, because all exported SVG files from Sketch / Illustrator should be rendered correctly.

**Comment by ystrot** [comment]
Closing this issue. Please reopen it with necessary details if it still appears.
