### ISSUE TITLE
[Q] Explicitly animating a Transform on a Node

### ISSUE THREAD

**Issue by galexite** [exyte/Macaw#133]
How do I animate an explicit Transform in Macaw? My app involves a compass, which is a `Node` on a `MacawView`. I only want to animate rotation, so what I really wanted was to do this:

```swift
myNode.placeVar.animate(transform: Transform.rotate(...))
```

Therefore retaining (but not modifying) my scaling set to `myNode.place`.

I do understand that there is `animate(to: Transform)`, but I loose my scaling. If I use `animate(to: myNode.place.rotate(...))`, I get rather weird issues with the node resizing almost seemingly randomly.

Is this possible in Macaw?

Thanks

**Comment by ystrot** [comment]
Hi George,

There is actually a special method for rotate animation:
```
myNode.placeVar.animate(angle: .pi)
```

This method can be used to rotate node around its center. You can also specify another point:
```
myNode.placeVar.animate(angle: .pi, x: x, y: y)
```
However these methods only available in the master version. You can switch to master by using:
```
pod 'Macaw', :git => 'https://github.com/exyte/Macaw.git'
```

**Comment by galexite** [comment]
`placeVar.animate(angle: Double)` doesn't seem to work as expected; i.e., my Node looks like this with no rotation called:

<img width="302" alt="Dial at 0 degrees" src="https://user-images.githubusercontent.com/6300838/27781700-02becbcc-5fc7-11e7-8d4b-b4d3939f4bc3.png">

As soon as I use `placeVar.animate(angle: Double)`:

<img width="301" alt="Dial at 30 degrees" src="https://user-images.githubusercontent.com/6300838/27781701-02bef638-5fc7-11e7-9881-407a4dd1ba7e.png">

**Comment by vhailor13** [comment]
Hello @galexite ,
Can you provide us .svg source of your node? It seems like there is special case for bounds calculation.  We will fix it asap.

**Comment by galexite** [comment]
I tried it with a brand new SVG of the same size and the same problem occurs (attached). I believe it is a problem with applying a scaling to the `Node`, and that this is being undone by `animate(angle: Double)`.

[test.svg.zip](https://github.com/exyte/Macaw/files/1118728/test.svg.zip)

**Comment by galexite** [comment]
Are the bounds changed when a Transform is set, I wonder?

**Comment by galexite** [comment]
@vhailor13 The rotation animation works when no scaling or positioning is applied to the `Node`. Therefore, the problem isn't the SVG, it's the calculation of the origin when the `Node` has had a `Transform` set to its `place`.

**Comment by galexite** [comment]
Requires issue #134 to be fixed first.

**Comment by vhailor13** [comment]
Fixed with f7c4acb22d308002dabfc77d3a18d099b1083b82. You can try it via **pod update** for master branch.  <img src="https://www.dropbox.com/s/39yltormg2wloed/rotation_fix_gif.gif?dl=1">

**Comment by galexite** [comment]
@vhailor13 Wow! Thanks! Testing now.

**Comment by galexite** [comment]
Solved. Thank you again @vhailor13!
