### ISSUE TITLE
Node created by `SVGParser.parse`: bounds do not change after a Transform is set

### ISSUE THREAD

**Issue by galexite** [exyte/Macaw#134]
Setting the `place` property of a `Node` created by `SVGParser.parse(path: ...)` to a `Transform`, for example, `Transform.scale`, does not alter its bounds, but it should.

**Comment by ystrot** [comment]
Hi George,

`Node.bounds` actually an internal function. Could you please describe your use case and explain why do you think bounds should be affected by `place` property?

**Comment by ystrot** [comment]
Closing this issue. Please reopen it if necessary.
