### ISSUE TITLE
.none instead nil

### ISSUE THREAD

**Issue by spromicky** [exyte/Macaw#135]
Hi! I found an interesting code in your project. Can you help me understand that? Why do you return `.none` instead of `nil` [here](https://github.com/exyte/Macaw/blob/master/Source/svg/SVGParser.swift#L187)?
Thanks.

**Comment by ystrot** [comment]
Hey! Sorry for late response, your ticket sparked a stormy discussion between our team members 😅. So let me share just my thoughts: there is almost no difference between `return .none` and `return nil`. I prefer the second way, however both are correct. Probably at some point we'll choose one way and will use it everywhere in the source code.

**Comment by spromicky** [comment]
Thanks for answering.
On my opinion `nil` is prefer. And in Apple's book about Swift everywhere used this way.
