### ISSUE TITLE
Carthage Build Error: No shared scheme for Mac platform

### ISSUE THREAD

**Issue by Kacper20** [exyte/Macaw#138]
Hi,

I've wanted to build this library for my macOS app by integrating it with Carthage. There is this error while trying to build: ```Dependency "Macaw" has no shared framework schemes for any of the platforms: Mac```.
Everything works fine for iOS. Could you please share scheme for macOS?

Best Regards,

Kacper

**Comment by ystrot** [comment]
Hi Kacper,

Unfortunately Macaw doesn't support macOS for now. We have another ticket for this task: #107.

**Comment by Kacper20** [comment]
Uh, sorry. Was tricked by this line in README: `iOS 8.0+ / Mac OS X 10.9+` :)
Thank you for such a fast response.

**Comment by ystrot** [comment]
Good point. I've removed Mac OS X mention from README, thanks!
