### ISSUE TITLE
Not sure how to Instantiate a MacawView class and provide NSCoder

### ISSUE THREAD

**Issue by jewilhel** [exyte/Macaw#140]
Hi Thanks for a great framework.

I have a question. I've made a macaw view like one of your examples:

```swift
import Foundation
import UIKit
import Macaw

class MacawScene: MacawView {
    required init?(coder aDecoder: NSCoder) {
        let shape = Shape(form: Rect(x: 5, y: 5, w: 175, h: 30),
                          fill: Color(val: 0xfcc07c),
                          stroke: Stroke(fill: Color(val: 0xff9e4f), width: 2))
        super.init(node: shape, coder: aDecoder)
    }
}
```

Now I'm trying to create an in code instance of this `MacawScene` class in my `ViewController` without using `StoryBoards` as the examples do. I don't know how to create an instance with the required `NSCoder` parameter used for initialization.

```swift
var macawScene = MacawScene(coder: NSCoder )
```
I would then proceed to add this as a subview to the view I'm working with in my code.
I'm sure I'm not understand something, but I couldn't find an example of how to do this.

Thanks in advance,

Jason W.

**Comment by ystrot** [comment]
Hi Jason,

You need to use another constructor to create `MacawView` programmatically. Take a look at one of these constructors:
1. `init(node: Node, frame: CGRect)`
2. `init(frame: CGRect)`

**Comment by ystrot** [comment]
Closing this issue. Please create a new one if you have more questions.
