### ISSUE TITLE
Pan/Horizontal Scroll

### ISSUE THREAD

**Issue by rejdic** [exyte/Macaw#142]
If I create a graph similar to the "Total of Steps" graph here 

https://camo.githubusercontent.com/0858db57496e5802ed511310896b44430b9ac551/687474703a2f2f692e696d6775722e636f6d2f725149683371442e676966

does it support panning or horizontal scroll if the entire graph doesn't fit the width of the screen?

**Comment by ystrot** [comment]
Sorry for late response, missed your question. Macaw doesn't provide any additional scroll capabilities, however MacawView is a regular UIView, so you can use standard iOS technics for scrolling.
