### ISSUE TITLE
Color fill animation in SVG affects unrelated shapes

### ISSUE THREAD

**Issue by pawurb** [exyte/Macaw#144]
Hello. I recently started playing around with your library. I noticed a bug when trying to change color of a Shape made from SVG file. You can see it on the following movie:

https://www.dropbox.com/s/f812e133elpn3p6/tiger_fill.mov?dl=0

I tried animating both fill and stroke and there is the same issue.

I prepared a clone of your repo reproducing the issue. I hooked up into library code for simplicity. I will grateful for any tips on how to resolve it.

https://github.com/pawurb/Macaw/tree/animation_issue

take care

**Comment by alan-andrade** [comment]
@pawurb new findings on this ?

**Comment by pawurb** [comment]
Nope. I ended up using a different lib for SVG

**Comment by ystrot** [comment]
Hi Paweł,

Sorry for missing your issue. If you'll find some time to recreate your clone repo we'll be glad to take a look at this.

**Comment by ystrot** [comment]
Closing this issue. Please reopen it with an example if necessary.
