### ISSUE TITLE
GestureRecognizer

### ISSUE THREAD

**Issue by al1020119** [exyte/Macaw#145]
How to Open GestureRecognizer?

**Comment by ystrot** [comment]
You can use Macaw evens to handle gestures on a Node: https://github.com/exyte/Macaw/wiki/Getting-started#events. Check out `onTouchPressed`, `onTouchMoved`, `onTouchReleased`, `onTap`, `onPan`, `onRotate`, `onPinch` methods.

**Comment by alan-andrade** [comment]
@al1020119 Was the answer useful. We can close if so. Thanks !

**Comment by ystrot** [comment]
Closing this issue. Please create a new one if you have some other questions.
