### ISSUE TITLE
Animation Slow/Choppy

### ISSUE THREAD

**Issue by rejdic** [exyte/Macaw#147]
Hi I'm doing something similar to the "Total Steps" graph you have in your examples:

https://camo.githubusercontent.com/0858db57496e5802ed511310896b44430b9ac551/687474703a2f2f692e696d6775722e636f6d2f725149683371442e676966

My graph has 19 columns and 20 Bar segment counts per column. When the graph goes to animate initially it is rendering very slow and choppy. I also saw that there are large CPU spikes during this time. Is there anyway to make the graph animate easier or be less GPU intensive?

**Comment by vhailor13** [comment]
Hello @rejdic ,
Do you use master branch or released version? Master branch currently contains new zPosition fix logic, which requires some more optimization.

**Comment by alan-andrade** [comment]
Hey @rejdic , did the answer work ? If so, can we solve this issue ?

Thanks !

**Comment by ystrot** [comment]
The current master version doesn't have serious lags, so both release and develop version should be fast enough to animate tens of objects.
