### ISSUE TITLE
Xcode 9 support

### ISSUE THREAD

**Issue by lwdupont** [exyte/Macaw#148]
Hello, 

I was trying to get a project use Macaw compiling under Xcode 9. Unfortunately in the cocoapods dependencies contains version 3 of SWXMLHash, which doesn't compile under Xcode 9. 

There is a version 4.0.0 of SWXMLHash that is Xcode 9 compatible. 

Any thoughts on updating and releasing a version with that change? I can do a pull request if desired.

**Comment by vhailor13** [comment]
Hello @lwdupont ,
Just added swift4 brach recently, it will be merged to master soon. You can try it via:

pod 'Macaw', :git => 'https://github.com/exyte/Macaw.git', :branch => 'swift4'

**Comment by lwdupont** [comment]
Ah, thanks. I'm sorry, I poked around but missed it. Will close this and give it a try. Thank you for the quick response :)

**Comment by lwdupont** [comment]
With the latest version of Xcode 9, I'm still getting some compile errors, specifically in the Text.swift file. FYI. (not going to reopen, will try later, or fork and fix it :))

**Comment by lwdupont** [comment]
Actually, I bet it's because I haven't flipped the Swift 4 flag yet for the whole thing. Will try, sorry to bug Ya.
