### ISSUE TITLE
Pinch to zoom svg

### ISSUE THREAD

**Issue by Atimca** [exyte/Macaw#150]
Hello! I'm using svgview on uiscrollview and trying to zoom it. But I have some issues with it.

![img_8332](https://user-images.githubusercontent.com/13145815/30053379-3d8a9f96-9231-11e7-8bd1-50cb72c89a06.PNG)
![img_8331](https://user-images.githubusercontent.com/13145815/30053383-417789ca-9231-11e7-9df6-664e02fbffb8.PNG)

When I'm using standard uiscroll methods, in the end, I have a fuzzy picture like on an image.

I tried to use this solution `https://github.com/exyte/Macaw/issues/113` but it is glitchy with my svg.

For now, I created svgView with 4th multiplier relatively scrollview. minimumZoomScale and zoomScale for scrollview 0.25. But I think it's not the best solution.

**Comment by vhailor13** [comment]
Hello @Atimca ,
I worked on same problem recently and found good solution. I created large MacawView (SVGView in your case)  e.g. 2000x2000 as UIScrollView's subview. And implemented delegate method:

 func viewForZooming(in scrollView: UIScrollView) -> UIView? {
        return svgView
 }

**Comment by Atimca** [comment]
Hello @vhailor13, so did I. But it's not very elegant solution. Although, for old devices such iPhone 4s. I had a memory warning, and if a base resolution is very high (if u want to see some small pieces in high resolution), u will have pixelated picture. 

One more solution is using uiscrollviewdelegate method "didEndZooming" and in it use some code from `https://github.com/exyte/Macaw/issues/113 `. However, it is still not an elegant way I think.

**Comment by 008v** [comment]
`swift
    @objc func handlePinch(gesture: UIPinchGestureRecognizer) {
        scale = Double(gesture.scale)
        let location = gesture.location(in: self)
        let anchor = Point(x: Double(location.x), y: Double(location.y))
        print("pinch(scale = \(scale), anchor = \(location.x, location.y))")
        node.place = Transform.move(dx: anchor.x * (1.0 - scale), dy: anchor.y * (1.0 - scale)).scale(sx: scale, sy: scale)
    }
`
here is my code.
I found a very strange phenomenon. One zoom is fine. When I zoom again, scale actually starts at 1.0
How to solve it ？

**Comment by ystrot** [comment]
You probably need to use something like this to keep your scale across different pinches:
```
let scale = self.scale * Double(gesture.scale)
if (gesture.state == .ended) {
    self.scale = scale
}
```

**Comment by ystrot** [comment]
Looks like all discussed issues were solved. So if there are some more issues please create new tickets.

**Comment by kritikaperiwal12** [comment]
I am showing SVG in webView but want to load SVG in zoomed scale already. How can I do this?

**Comment by ystrot** [comment]
Hi @kritikaperiwal12 ,

It's better to open another ticket for your question, because here it might be easily missed. Here is a tutorial on how to show SVG in Macaw: https://github.com/exyte/Macaw/wiki/Getting-started#svg

**Comment by kritikaperiwal12** [comment]
@ystrot Ok, I will create a new ticket for this. Thanks for the link.
