### ISSUE TITLE
Implement/fix transform for shapes

### ISSUE THREAD

**Issue by kayuri** [exyte/Macaw#171]
Add proper support for transform in shapes and text: 
```
<text transform="rotate(90) translate(120 -100)" text-anchor="middle">Rotated 90 degrees</text>```

**Comment by f3dm76** [comment]
I believe it's working as expected, here is a picture
<img width="273" alt="screen shot 2018-07-20 at 12 39 32" src="https://user-images.githubusercontent.com/9447630/42985069-fcbbd064-8c19-11e8-9db3-20938370fa0a.png">
