### ISSUE TITLE
Content Mode doesn't work

### ISSUE THREAD

**Issue by cuong1112035** [exyte/Macaw#218]
Hi, thank for your library. 
I created a view with specific frame and setting Scale To Fill for content mode but It doesn't work. Did I miss something?

**Comment by ystrot** [comment]
Could you please attach an SVG that doesn't work for you?

**Comment by cuong1112035** [comment]
@ystrot  I got the tiger svg from your git example

**Comment by ystrot** [comment]
I've checked Example project and with Scale To Fill it looks quite fine: 
![tiger](https://i.imgur.com/SfWXL1t.png)

If it doesn't work for you, could you please provide more details like screen shot, Macaw version, etc? If you can attach your project it will be really helpful.

**Comment by cuong1112035** [comment]
hi @ystrot 
I attach a demo project here
[1 Getting Started.zip](https://github.com/exyte/Macaw/files/1503959/1.Getting.Started.zip)

**Comment by amarunko** [comment]
Hi, @cuong1112035, MacawView doesn't support contentMode functional, only SVGView class from Macaw library support this UIView functional (I've trued with you project - everything work as expected). We can suggest you to use SVGView if possible, if not, you can just copy&paste SVGView implementation to your code and customise it as you like. Reference to SVGView content mode implementation: https://github.com/exyte/Macaw/blob/master/Source/svg/SVGView.swift#L66-L144

We will add this functional to later releases, thanks.

**Comment by ystrot** [comment]
Both `MacawView` and `SVGView` now support content mode, see https://github.com/exyte/Macaw/wiki/Understanding-MacawView-content-layout for details.
