### ISSUE TITLE
SVG-rendering: change colors etc.

### ISSUE THREAD

**Issue by Lupurus** [exyte/Macaw#222]
What do you think about adding the possibility to make SVG-rendering more flexible? It would be perfect to load one svg-file but replace maybe some of the fill colors. I'm actually checking the code, but I would suggest sth. like this (and I will post my results as soon, as I could solve the problem):

You're loading the SVG via `SVGParser.parse(...)`. I would suggest to add one more parameter, so that you can call like this:

```
let myParsingOptions = [ParsingOption(id: "someId", attribute: .fill, newAttribute: NSColor.red), ...]

SVGParser.parse("myFile", myParsingOptions)
```

I will search in the SVGParser.swift file, where I have to make the changes.

**Comment by Lupurus** [comment]
Aaah sorry, this one can be closed. I found this solution, that's much easier (although I don't really understand, why it's `nodeBy(tag: ...)` (why tag?)

https://github.com/exyte/Macaw/issues/219#issuecomment-344229031

I really love Macaw, thank you so much. With this way it's nearly a complete replacement for PaintCode! (I still hesitated buying the new version)

**Comment by ystrot** [comment]
Thanks you! Good to know you found solution. Macaw model is much more flexible then SVG. SVG node has one id while Macaw node can have multiple identifiers, that's why we call it tag instead of id.

**Comment by Lupurus** [comment]
Ah, that's cool. I extended `SVGView` for my purpose. Maybe you could think about it using it in a following version?

```
	fileprivate enum ChangeAttribute {
		case fillColor
		case stroke
		case strokeWidth
		case strokeColor
	}
	
	/** recursive function to set the changement of all shapes */
	fileprivate func changeAttribute(group: Group, attribute: ChangeAttribute, change: Any) {
		group.contents.forEach { content in
			if content is Group {
				self.changeAttribute(group: content as! Group, attribute: attribute, change: change)
			} else if let shape = content as? Shape {
				switch(attribute) {
				case .fillColor:
					if let fillColor = change as? NSColor {
						// convert using Colorspace, otherwise the app will crash
						if let tmpColor = fillColor.usingColorSpace(NSColorSpace.deviceRGB) {
							shape.fill = Color.rgba(r: Int(tmpColor.redComponent*255.0), g: Int(tmpColor.greenComponent*255.0), b: Int(tmpColor.blueComponent*255.0), a: Double(tmpColor.alphaComponent))
						}
					}
				case .stroke:
					if let c = change as? Bool {
						if c == false {
							self.tmpStroke = shape.stroke	// tmp save the stroke
							shape.stroke = nil
						} else {
							shape.stroke = self.tmpStroke
						}
					}
				case .strokeWidth:
					if let strokeWidth = change as? Double {
						if shape.stroke != nil {	// only changes, if there is already a stroke
							let newStroke = Stroke(fill: shape.stroke!.fill, width: strokeWidth, cap: shape.stroke!.cap, join: shape.stroke!.join, dashes: shape.stroke!.dashes)
							shape.stroke = newStroke
						}
					}
				case .strokeColor:
					if let strokeColor = change as? NSColor {
						if shape.stroke != nil {	// only changes, if there is already a stroke
							// convert using Colorspace, otherwise the app will crash
							if let tmpColor = strokeColor.usingColorSpace(NSColorSpace.deviceRGB) {
								let newStroke = Stroke(fill: Color.rgba(r: Int(tmpColor.redComponent*255.0), g: Int(tmpColor.greenComponent*255.0), b: Int(tmpColor.blueComponent*255.0), a: Double(tmpColor.alphaComponent)), width: shape.stroke!.width, cap: shape.stroke!.cap, join: shape.stroke!.join, dashes: shape.stroke!.dashes)
								shape.stroke = newStroke
							}
						}
					}
				}
			}
		}
		self.render()
	}
	
	/**
	* the rootFillColor sets the fill color of everything in the SVG
	*/
	var rootFillColor: NSColor? {
		didSet {
			changeAttribute(group: self.rootNode, attribute: .fillColor, change: rootFillColor!)
		}
	}
	
	fileprivate var tmpStroke: Stroke? = nil
	/** Bool value, whether there is a stroke */
	var stroke: Bool? {
		didSet {
			self.changeAttribute(group: self.rootNode, attribute: .stroke, change: stroke!)
		}
	}
	
	var strokeWidth: Double? {
		didSet {
			self.changeAttribute(group: self.rootNode, attribute: .strokeWidth, change: strokeWidth!)
		}
	}
	
	var strokeColor: NSColor? {
		didSet {
			self.changeAttribute(group: self.rootNode, attribute: .strokeColor, change: strokeColor!)
		}
	}
```

**Comment by Lupurus** [comment]
I think, that no one saw this last suggestion. Any way to bring sth. like this in the main code? Writing this as an extension doesn't work without changing the code of `SVGView.swift`, because `rootNode` is `fileprivate`, as well the `func render()`

**Comment by ystrot** [comment]
Thank you for suggestion. However I think it's not that general to include it to the main codebase and it can be easily implemented by a user. You mentioned that you can't implement it because of limitations of `SVGView` and that's because `SVGView` just about rendering existing SVG files from the storyboard. And if you want to change something you need to use `MacawView` directly.

I know there is one issue that `SVGView` has content mode while `MacawView` has not, but we'll fix it.

**Comment by Lupurus** [comment]
Hey, thanks for your answer. I understand, that an extension would be better. But: Why don't you make `rootNode` and `render()` public? In `MacawView.swift` the `node` is also an `open var`. I just did that now for me to make an `extension` from the code above.

**Comment by ystrot** [comment]
Do you have any other questions regarding this topic or I can close this issue? Again, `rootNode` and `render` couldn't be public because they are not part of public API and can be changed in the future. We'll move all features from `SVGView` to `MacawView` which is intended to be extended.

**Comment by ystrot** [comment]
I'm closing this issue, please reopen it if you have other questions.

**Comment by jcnolan** [comment]
Thank you Lupurus for your great work on this.  I was able to make it work pretty much plug-and-play from your code sample, but was able to make the subclass work w/out touching Macaw.  Seems to be working fine for my needs though I'm just starting to test it

`

import Cocoa
import Macaw

class SVGColorView: SVGView {
    
    fileprivate enum ChangeAttribute {
        case fillColor
        case stroke
        case strokeWidth
        case strokeColor
    }
    
    var rootNode: Group = Group()
    
    override var node: Node {
        get {
            return super.node
        }
        set {
            super.node = newValue
            self.rootNode = Group(contents: [newValue])
        }
    }
    
    /** recursive function to set the changement of all shapes */
    fileprivate func changeAttribute(group: Group, attribute: ChangeAttribute, change: Any) {
        group.contents.forEach { content in
            if content is Group {
                self.changeAttribute(group: content as! Group, attribute: attribute, change: change)
            } else if let shape = content as? Shape {
                switch(attribute) {
                case .fillColor:
                    if let fillColor = change as? NSColor {
                        // convert using Colorspace, otherwise the app will crash
                        if let tmpColor = fillColor.usingColorSpace(NSColorSpace.deviceRGB) {
                            shape.fill = Color.rgba(r: Int(tmpColor.redComponent*255.0), g: Int(tmpColor.greenComponent*255.0), b: Int(tmpColor.blueComponent*255.0), a: Double(tmpColor.alphaComponent))
                        }
                    }
                case .stroke:
                    if let c = change as? Bool {
                        if c == false {
                            self.tmpStroke = shape.stroke    // tmp save the stroke
                            shape.stroke = nil
                        } else {
                            shape.stroke = self.tmpStroke
                        }
                    }
                case .strokeWidth:
                    if let strokeWidth = change as? Double {
                        if shape.stroke != nil {    // only changes, if there is already a stroke
                            let newStroke = Stroke(fill: shape.stroke!.fill, width: strokeWidth, cap: shape.stroke!.cap, join: shape.stroke!.join, dashes: shape.stroke!.dashes)
                            shape.stroke = newStroke
                        }
                    }
                case .strokeColor:
                    if let strokeColor = change as? NSColor {
                        if shape.stroke != nil {    // only changes, if there is already a stroke
                            // convert using Colorspace, otherwise the app will crash
                            if let tmpColor = strokeColor.usingColorSpace(NSColorSpace.deviceRGB) {
                                let newStroke = Stroke(fill: Color.rgba(r: Int(tmpColor.redComponent*255.0), g: Int(tmpColor.greenComponent*255.0), b: Int(tmpColor.blueComponent*255.0), a: Double(tmpColor.alphaComponent)), width: shape.stroke!.width, cap: shape.stroke!.cap, join: shape.stroke!.join, dashes: shape.stroke!.dashes)
                                shape.stroke = newStroke
                            }
                        }
                    }
                }
            }
        }
        self.draw(NSRectToCGRect(self.bounds))
//        self.render()
    }
    
    /**
     * the rootFillColor sets the fill color of everything in the SVG
     */
    var rootFillColor: NSColor? {
        didSet {
            changeAttribute(group: self.rootNode, attribute: .fillColor, change: rootFillColor!)
        }
    }
    
    fileprivate var tmpStroke: Stroke? = nil
    /** Bool value, whether there is a stroke */
    var stroke: Bool? {
        didSet {
            self.changeAttribute(group: self.rootNode, attribute: .stroke, change: stroke!)
        }
    }
    
    var strokeWidth: Double? {
        didSet {
            self.changeAttribute(group: self.rootNode, attribute: .strokeWidth, change: strokeWidth!)
        }
    }
    
    var strokeColor: NSColor? {
        didSet {
            self.changeAttribute(group: self.rootNode, attribute: .strokeColor, change: strokeColor!)
        }
    }
}
}
`

**Comment by JoachimM7** [comment]
Unfortunately this solution doesn't work for me (anymore). Didn't yet figure out why, but are there any changes in the meantime, that would support sth. like this? [SwiftSVG](https://github.com/mchoe/SwiftSVG) supports this (look at the Readme), but I like Macaw more.

**Comment by jcnolan** [comment]
Greetings all, I'm back looking at this code for colorizing SVGs after a couple years and it seems to be working well for me still.  However one additional thing I'd like to do is set the background color for the view.  Simply setting the .backgroudColor of the view after creating it does not seem to have an impact.  
'''
      func svgToNSImage(resourceName: String, size: CGSize, color:NSColor?=nil) -> NSImage? {
        
        let rootNode = self.getSVG(fullPath: resourceName, elideCache:true)
        let macawView = SVGColorView(node: rootNode, frame: CGRect(origin: CGPoint.zero, size: size))
        macawView.wantsLayer = true
        
        if let color = color {
            macawView.rootFillColor = color
            macawView.strokeColor = color
        }
        
        macawView.backgroundColor = .red // has no effect :(
        
        let image:NSImage = macawView.node.toNativeImage(size: Size(w: Double(size.width), h: Double(size.height)))
        return image
    }
'''

**Comment by ystrot** [comment]
Actually you don't need `MacawView` to create an image, that's why any changes to the view don't have effect. You need to manipulate node itself, something like:
```swift
let rootNode = self.getSVG(fullPath: resourceName, elideCache:true)
let background = Rect(0, 0, Double(size.width), Double(size.height)).fill(Color.red)
let group = Group(contents: [background, rootNode])
return group.toNativeImage(size: Size(w: Double(size.width), h: Double(size.height)))
```

**Comment by jcnolan** [comment]
Thanks ystrot but that doesn't seem to be getting me what I want.  In my case, my original code will take a B/W SVG and render it in any color I give it, on a white background (see my comment above dated on Oct 8, 2018 for that code).  Now, what I'm wanting to do is generate the colored SVG on a background of a different color.  The code above does indeed give me a swatch of RED that is the size of my icon (rootNode) ... but the icon is not visible - just a red box
