### ISSUE TITLE
SVG is removed after ContentsVar animation finishes

### ISSUE THREAD

**Issue by FadyAckad** [exyte/Macaw#223]
Hi,
I try to animate an SVG using to the following code.

`let rootNode = try SVGParser.parse(path: "frame0")`
`let rootGroup = [rootNode].group()`
`self.svgView.node = rootGroup`
`let endNode = try SVGParser.parse(path: "frame2")`
`rootGroup.contentsVar.animate(from: rootGroup, to: [endNode], during: animationDuration, delay: 0)`

And it works, but after the animation is finished the SVG is removed and the view is left blank.

![screenshot](https://user-images.githubusercontent.com/18596351/32992736-f0687948-cd56-11e7-8dff-948240c6abbb.gif)

**Comment by ystrot** [comment]
Which version are you using? I believe such an issue should be fixed in a master branch. If you can check it out and it still doesn't work even on master, could you please attach your SVG files?

**Comment by FadyAckad** [comment]
I'm using the latest version "0.9.0"

I've tried setting the final node manually after the animation is finished, and that works but there's a flash for a part of a second.

You can download the SVGs using the following link:
[Frames.zip](https://drive.google.com/open?id=1ZYdsyBj4Q767b1WOO0YEkRKB9rwGAmUk)

**Comment by ystrot** [comment]
I checked your sample and this issue actually fixed in the latest version. You can wait for a release version (later this year), or use master branch:
```
pod 'Macaw', git: 'https://github.com/exyte/Macaw.git'
```

**Comment by ystrot** [comment]
Fixed in 0.9.1
