### ISSUE TITLE
Build Failed when run 'carthage update --platform iOS`

### ISSUE THREAD

**Issue by mvnrc** [exyte/Macaw#226]
When I try to build the carthage, I receive the following error:

```
Check dependencies
No architectures to compile for (ARCHS=armv7 arm64, VALID_ARCHS=x86_64 i386).
warning: no umbrella header found for target 'Macaw', module map will not be generated
```

_my cartfile is:_ **github "Exyte/Macaw" ~> 0.9.0**

I also tried  `carthage update --platform ios --no-use-binaries` but the same error!

**Comment by vhailor13** [comment]
Hello @mvnrc ,
Recently we released version 0.9.1 with fix.
