### ISSUE TITLE
Need a Demo Morphing project.

### ISSUE THREAD

**Issue by Bat-Orshikh** [exyte/Macaw#227]
I need a real project of above wiki's project.https://github.com/exyte/Macaw/wiki/Morphing-animation

**Comment by Bat-Orshikh** [comment]
I can't run above example morphing shapes.

**Comment by ystrot** [comment]
You may find one of the wiki's examples right in the Example project: https://github.com/exyte/Macaw/tree/master/Example.

Here is MorphingView source code which is quite similar to the wiki: https://github.com/exyte/Macaw/blob/master/Example/Example/Examples/Morphing/MorphingView.swift

Then you can modify MorphingView locally and use code samples from the wiki, everything should work fine. For the last sample I couldn't find exactly these two animals, however you can use any two SVG files. For example, you can use nice sample from the one of the recent tickets: https://github.com/exyte/Macaw/issues/223#issuecomment-345630774

**Comment by Bat-Orshikh** [comment]
I want to run this one but IDK how to do https://camo.githubusercontent.com/d9df4ef4b86715aa4469bd561821db3c1d121a24/687474703a2f2f692e696d6775722e636f6d2f6b7573774235552e676966

**Comment by ystrot** [comment]
You can do following:
* check out example project: https://github.com/exyte/Macaw/tree/master/Example
* open `MorphingView`
* replace content of the `newScene` method with the sample you need:
```swift
let form1 = Rect(x: 50.0, y: 50.0, w: 200.0, h: 200.0)
let form2 = Circle(cx: 150.0, cy: 150.0, r: 100.0)
        
let shape = Shape(form: form1, stroke: Stroke(width: 3.0))
let animation = shape.formVar.animation(to: form2, during: 1.5, delay: 2.0)
animation.autoreversed().cycle().play()
return shape
```

Then you can create your own project using `Example` as a template.

**Comment by Bat-Orshikh** [comment]
thank you.

**Comment by Bat-Orshikh** [comment]
@ystrot Can I draw custom path(shape)? If yes, give me some instruction. Thanks for your support. 😃

**Comment by ystrot** [comment]
Regarding drawing custom path - you can start from this sample:
```swift
let path = MoveTo(x: 10, y: 10)
	.lineTo(x: 20, y: 20)
	.lineTo(x: 10, y: 20)
	.close().build()
		
let shape = Shape(form: path, fill: Color.red)
```

Macaw works with SVG path segments, so you could learn more about available options using SVG documentation: https://www.w3.org/TR/SVG/paths.html
