### ISSUE TITLE
iOS minimal version set to 9.1

### ISSUE THREAD

**Issue by gdurys** [exyte/Macaw#234]
Is there a real reason to have iOS 9.1 as a minimal version?

**Comment by ystrot** [comment]
Do you need 9.0 or earlier version?

**Comment by gdurys** [comment]
The project I work on has 9.0 as minimum.

**Comment by ystrot** [comment]
We made it 9.1 by mistake during release of Macaw 0.9.1. Will fix it, for now you can switch to version 0.9.0.

**Comment by gdurys** [comment]
Great.
Thanks.

**Comment by amarunko** [comment]
Hi, @gdurys , we make changes for version in master branch, you can change in pod file:

pod 'Macaw', :git => 'https://github.com/exyte/Macaw.git'

Thanks, please, reopen issue when get troubles
