### ISSUE TITLE
Make bounds() not optional and as a var

### ISSUE THREAD

**Issue by Lupurus** [exyte/Macaw#240]
Two suggestions:

1) Why is `bounds()` optional? It's a little bit annoying always to unwrap it. Only in the `Image`-class there is the possibility, that there will be no `Rect` as a return. So maybe you could only make this one optional?

2) As in the newer Swift-versions it would be nicer, if bounds is a property and not a function?

**Comment by ystrot** [comment]
Thanks for your comments! I agree with you, but it actually makes implementation much more complicated. However we decided to provide quick and working solution for now and then make it optimal. Regarding property/method - I don't think it makes a lot of sense. It can't be assigned and implementation looks too complicated for a "property".

I'm closing this ticket and if you have more comments please let's keep discussion in a single place here: https://github.com/exyte/Macaw/issues/252
