### ISSUE TITLE
Text bounds not supporting font weight

### ISSUE THREAD

**Issue by Lupurus** [exyte/Macaw#241]
The `bounds()`-function in the `Text.swift` only returns the size of the normal weighted font. So for bold fonts for example the bounds are wrong. Line no. 95 should be changed to:

`font = MFont.systemFont(ofSize: CGFloat(f.size), weight: getWeight(f.weight))`

As well you have to copy the getWeight-function, but I would suggest to return `MFont.Weight.regular` as default.

**Comment by ystrot** [comment]
Thanks for reporting! Your proposal looks good. Did you think about creating a pull request to keep your authorship for all your work?

**Comment by Lupurus** [comment]
I'll try, but I have to admit, that I still don't understand, how I can do that on Github. But I will look for it ;)

**Comment by zapletnev** [comment]
Hi @Lupurus 

To make a PR you should do next:
1) Make a fork of exyte/Macaw repository
2) Make a new branch for specific task in your fork (for example, text_bounds_fix)
3) Make required changes + commit it
4) Go back to exyte/Macaw and make a new PR from your local branch to exyte/Macaw master branch.

Good luck!

**Comment by Lupurus** [comment]
Thank you!! I tried that, I hope I did it right :)
