### ISSUE TITLE
Node Tap handler breaks after animating

### ISSUE THREAD

**Issue by OskarGroth** [exyte/Macaw#249]
I have a `Node` set up like this using Macaw on iOS:

```
let bar = Shape(
    form: Rect(x: Double(x), y: Double(y), w: Double(width), h: Double(height)),  
    fill: point.color.macawColor
)
```

To which I add a tap event handler:

```
bar.onTap { tapEvent in
    print("Tap")
    bar.fillVar.animation(to: UIColor.red.macawColor, during: 1, delay: 0).autoreversed().play()
}
```

**Expected:** 
All taps prints "Tap" and animates the bar.

**What happened:**
The first tap get registered, prints "Tap" and triggers an animation.
However, consecutive taps to the same node are never registered.

If I remove the animation, consecutive taps will print "Tap" just fine.

![barss](https://user-images.githubusercontent.com/1417019/33760138-fe97c4e4-dc04-11e7-89db-4c80a26b4aba.gif)

**Comment by ystrot** [comment]
Thanks for reporting! We reproduced this issue and I think it will be fixed soon.

**Comment by ystrot** [comment]
Fix of this issue available in the master branch and will be part of the 0.9.2 release.
