### ISSUE TITLE
Getting Unsupported Locus

### ISSUE THREAD

**Issue by RaghavMangrola** [exyte/Macaw#251]
I've created a sample project here https://github.com/RaghavMangrola/MacawTesting.

All I've done is added an SVG View to the ViewController and I'm loading in an SVG file of a CryptoKitty. I'm not too familiar with how SVG's work but when I load the app I'm getting the fatal error "Unsupported locus" in Locus+ToPath.swift line 73

**Comment by ystrot** [comment]
Hi Raghav. Thanks for reporting, we'll take a look!

**Comment by ystrot** [comment]
I took a look into this issue. The fix of original error is quite simple, so it'll be available soon in the master version and you will be able to render your kitty without errors. However there are a lot of other issues related to SVG parser which makes rendering wrong. We're still working on the SVG parser and unfortunately it's far from ideal. Anyway we'll try to prioritize issues related to parsing of your SVG file. Will keep you updated!

**Comment by ystrot** [comment]
Finally your SVG works quite well. All fixes in the master version and will be part of 0.9.2 release.

**Comment by RaghavMangrola** [comment]
Thanks so much! I appreciate it!
