### ISSUE TITLE
SwiftPM 4 could not build up .

### ISSUE THREAD

**Issue by ACChe** [exyte/Macaw#256]
Using SwiftPM 4 could not setup the project.

error back below:

`error: noManifest(baseURL: "https://github.com/exyte/Macaw.git", version: Optional("0.9.1"))`

What is the problem?

**Comment by ystrot** [comment]
Sorry, we're working on Swift Package Manager right now and it's only in developer version. We just removed such a section from readme to avoid confusion and will provide full support together with version 0.9.2.

**Comment by ACChe** [comment]
And a  question on build on Carthage part, it could not build out the library for macOS, but iOS is normal.

**Comment by ystrot** [comment]
Finally we decided to avoid SwiftPM support, because it doesn't support iOS and designed for other type of projects.

**Comment by MhdHejazi** [comment]
> because it doesn't support iOS and designed for other type of projects.

May I ask what did you mean with that?
I tried adding `Package.swift` file and everything worked just fine. Maybe things have changed since then?
