### ISSUE TITLE
Advanced clipping support for SVG

### ISSUE THREAD

**Issue by ystrot** [exyte/Macaw#257]
In Macaw, `clip` is a `Locus` which is currently quite limited. In SVG you can combine paths, make transformation, etc. to define a clip. It's a difficult task to implement all possible path transformations, however we can do a trick for better SVG support.

We can create a custom `Locus` which will be wrapped for `UIBezierPath` and use its power for difficult cases.

**Comment by JohnKuan** [comment]
Hi @ystrot,

May I know if there will be a substantial explanation on this feature when it has been released? Perhaps a simple example showcasing the clip methods that will be available would be good.

I have a particular layout I wish to be able to draw using this library which involves two circular clips to a pair of `roundedRects`. May I know if the coming update will be able to support this layout?

![screenshot 2018-05-20 23 01 21](https://user-images.githubusercontent.com/4402214/40280144-bd49e76c-5c81-11e8-961e-a93f385e5e8c.png)

Thank you and the team for this amazing library.

**Comment by ystrot** [comment]
Hi John,

Actually your task doesn't require advanced clipping mentioned in this task. All you need is clip your shapes with a `Path` created using set of lines and arcs. Something like that:
```swift
let clipPath = MoveTo(x: 50, y: 50)
    .lineTo(x: 200, y: 50)
    .arcTo(rx: 10, ry: 10, angle: .pi / 2, largeArc: false, sweep: true, x: 210, y: 60)
    .lineTo(x: 210, y: 200)
    .arcTo(rx: 10, ry: 10, angle: .pi, largeArc: false, sweep: false, x: 210, y: 220)
    ...
    .build()

```

**Comment by ystrot** [comment]
Current clipping already good enough. In case of some edge cases other issues may be opened.
