### ISSUE TITLE
NodeRenderer crashes

### ISSUE THREAD

**Issue by Lupurus** [exyte/Macaw#259]
Hi. Simple problem: Adding a `SVGView` and setting the filename to a file, that doesn't exists, crashes the app. This is because of the forced downcast in `NodeRenderer.swift` at line 74 in the `render()` func. The `cgContext` will never be set. So I would suggest to just `return`, if the cgContext is `nil`.

I know, that this cases would be rare, but what if someone leads to SVG files, set by the user? And if he moved it? What would be better... checking if the file exists or just return, if cgContext is nil?

**Comment by amarunko** [comment]
Hi, @Lupurus, I think sometimes crash is better way for finding issue, instead of nothing happening

**Comment by Lupurus** [comment]
You're right, but usually that's only ok when developing. But I forgot, that `SVGView` actually not supports loading svgs from outside the bundle. So my case is only limited to the case, that the svg is not in the bundle. Then it's really a developer problem ;) Sorry for that useless issue, I'm closing it now.
