### ISSUE TITLE
Animate per path of svg

### ISSUE THREAD

**Issue by dmwesterhoff** [exyte/Macaw#262]
Trying to figure out how to animate each path individually in my svg, it seems like this is possible but am not totally sure.

This is the SVG:
```
<svg
    xmlns="http://www.w3.org/2000/svg"
    width="1132"
    height="100"
    viewBox="0 0 1132 100">
    <g id="start_block">
      <path
        d="M 3 33 C 3 3 3 3 33 3 L 297 3 L 237 97 L 33 97 C 3 97 3 97 3 67 Z"
        fill="#dfe4e6"/>
    </g>
    <g id="mid_block_1">
      <path
        d="M 323 3 L 583 3 L 523 97 L 263 97 Z"
        fill="#dfe4e6"/>
    </g>
    <g id="mid_block_2">
      <path
        d="M 609 3 L 869 3 L 809 97 L 549 97 Z"
        fill="#dfe4e6"/>
    </g>
    <g id="end_block">
      <path
        d="M 895 3 L 1099 3 C 1129 3 1129 3 1129 33 L 1129 67 C 1129 97 1129 97 1099 97 L 835 97 Z"
        fill="#dfe4e6"/>
    </g>
</svg>
```

And I'm trying to change animate the fill color of each 'block' programmatically in a piecewise fashion. Is this supported?

**Comment by vhailor13** [comment]
Hello @dmwesterhoff , 
There is brief guide for shape animations [https://blog.exyte.com/macaw-ios-library-morphing-animations-and-touch-events-a4cb1c0be97f](https://blog.exyte.com/macaw-ios-library-morphing-animations-and-touch-events-a4cb1c0be97f)
And some example for your case:

        let testGroup = try! SVGParser.parse(path: "test")  as! Group
        testGroup.place = .scale(sx: 0.2, sy: 0.2)
        let startBlockShape = (testGroup.nodeBy(tag: "start_block") as! Group).contents.first as! Shape
        let animation = startBlockShape.fillVar.animation(to: Color.red).autoreversed().cycle()
        animation.play()

![start_block](https://user-images.githubusercontent.com/735785/34511826-d084393e-f090-11e7-84a4-db1c43696b4c.gif)

**Comment by ystrot** [comment]
Closing this issue. You could open another one if you have more questions.
