### ISSUE TITLE
Unable to find a target named `Macaw`, did find `Example`

### ISSUE THREAD

**Issue by meharv** [exyte/Macaw#263]
Please suggest what shall i do now? U nable to install the dependencies

**Comment by ystrot** [comment]
Could you please provide more details on how do you use Macaw.

Did you run "pod install" in Macaw/Example directory? Did you open "Example.xcworkspace"?

**Comment by meharv** [comment]
Thank you so much for taking out time to reply my query.
Yes I was trying to run pod install- error: Unable to find a target named `Macaw`, did find `Example`, When I try to run Example.xcworkspace i do get error and one of the reason is i am unable to install above POD. Let me try to share the screen shot also, in the mean can you also try to run the same pod file.

**Comment by f3dm76** [comment]
If you still have problems with pod installation, please reopen
