### ISSUE TITLE
SVGView padding between image and border

### ISSUE THREAD

**Issue by donhill** [exyte/Macaw#265]
Hi,
I am using SvgView and have added a border. it seems the image take up the whole view and I would like to add some padding between the border and the image.

Is this possible with the stock SvgView ? If now could I get some guidance?
<img width="67" alt="screen shot 2018-01-13 at 10 00 31 am" src="https://user-images.githubusercontent.com/201891/34907734-a22073e0-f848-11e7-8229-53e37cf4aba4.png">

**Comment by donhill** [comment]
I am not sure if my solution if the right way. I added a view/container that is the parent of the svgView. I then added the border to the container to get the effect

**Comment by ystrot** [comment]
Solution with a container is fine, so feel free to use it.

**Comment by ystrot** [comment]
Closing this issue. You could open another one if you have more questions.
