### ISSUE TITLE
Support for animated SVG ?

### ISSUE THREAD

**Issue by mackoj** [exyte/Macaw#266]
I would like this to work [Ghost-animate.svg.zip](https://github.com/exyte/Macaw/files/1631859/Ghost-animate.svg.zip), how can I help to adding support for animated SVG ?

Thanks for your library,

**Comment by OskarGroth** [comment]
There is already frameworks like [Lottie](http://airbnb.io/lottie/) to do this.

**Comment by mackoj** [comment]
I don't use lottie because we don't use AfterEffect only animated SVGs.

**Comment by ystrot** [comment]
Unfortunately we don't support SVG animation for now. We have this task on our roadmap, but it's not an easy one and most likely will be implemented after a few months.

**Comment by mackoj** [comment]
Ok thanks
