### ISSUE TITLE
Ellipses don't seem to be rendering correctly

### ISSUE THREAD

**Issue by mdonati** [exyte/Macaw#271]
I took this example https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/cartman.svg and it doesn't render it correctly. Nose ellipse seems missed while eyes/eyeballs seem incorrectly sized and misplaced. I see no message in the console so I assume parsing ends up successfully.

<img width="428" alt="captura de pantalla 2018-02-05 a la s 11 57 04" src="https://user-images.githubusercontent.com/905200/35810885-e3a56566-0a6b-11e8-86ce-690eb9fc426e.png">

`
let view = SVGView(frame: self.frame)
        view.fileName = "cartman"
        view.contentMode = .scaleAspectFit
        self.view.addSubview(view)
`

Is there any configuration I'm missing?

**Comment by ystrot** [comment]
We reproduced this issue and your configuration is fine, it's just a bug in SVG parser. We'll take a look. Thanks for reporting!

**Comment by ystrot** [comment]
These issues fixed in the master branch and will be part of 0.9.2 release.
