### ISSUE TITLE
Rotate to Specific Point/Degree Count ?

### ISSUE THREAD

**Issue by Vinz1911** [exyte/Macaw#272]
Is it possible to rotate to a specific Degree Count. I want to build a Gauge with Macaw, I have a Line-Shape added and I want to rotate this Line to a Specific Degree Count. For Example i want to build a function to rotate to a specific degree count and not add a new animation after it reaches the given degree count ? How can I reach this ?

**Comment by ystrot** [comment]
I'm not sure I understood you correctly, but you can use one of the following function to rotate your shape:
```swift
// rotate to 180 degrees around (0, 0) point
shape.place = .rotate(angle: .pi)
// rotate to 90 degrees around (cx, cy) point
shape.place = .rotate(angle: .pi / 2, x: cx, y: cy)
// animate rotation to 180 degrees. Use other arguments to customize animation
shape.placeVar.animate(angle: .pi)
```

**Comment by Vinz1911** [comment]
Thanks very much, this have solved my Problem :)
The Problem was caused by using this 
`shape.place = shape.place.rotate(angle: .pi / 2, x: cx, y: cy)` instead of
`shape.place = .rotate(angle: .pi / 2, x: cx, y: cy)`

thanks 👍

**Comment by ystrot** [comment]
Great! Thanks for using Macaw!
