### ISSUE TITLE
[Question] SVG Standards support

### ISSUE THREAD

**Issue by salvasp** [exyte/Macaw#273]
Is there any indication on the SVG formats supported?
Compressed (svgz), 1.0, 1.1, Tiny, Bacis...
I see this export options in Illustrator but but not all of them are successfully processed.
Frequently i get something like the issue #271 , sometimes i get a black and white image "like a silhouette"
This also happen with the SVG of OpenClipart

**Comment by ystrot** [comment]
We don't support compressed SVG right now and we're working on 1.1 version support. So I would recommend you:
* use master branch to have latest SVG features
* export to 1.1 and try it
* if it doesn't work, create an issue

**Comment by ystrot** [comment]
Closing this issue. Please reopen it or create a new one if you have other questions.
