### ISSUE TITLE
image question

### ISSUE THREAD

**Issue by DouglasGLewis** [exyte/Macaw#279]
I want to (in macOS app) take a screenshot and add it to my MacawView view. I'm only seeing SVG format. What about png format images? 

I tried to load my images this way. I get no error but also no image is visible:
mycanvas.wantsLayer = true
mycanvas.layer!.contents = NSImage(named:NSImage.Name(rawValue:"testimage"))

Any ideas?

**Comment by ystrot** [comment]
Hi Douglas,

Just use [Image](https://github.com/exyte/Macaw/wiki/Getting-started#image) as a node in your `MacawView`. You may use `.image()` extension to convert your `NSImage` to Macaw `Image`.

**Comment by DouglasGLewis** [comment]
Okay, that's a help but the image still isn't visible. Here is a snipit of my test code. The text shows but the image doesn't. I've verified the image is a good path. Any ideas?

required init?(coder aDecoder: NSCoder) {
        let text = Text(text: "Hello, World I'm back and I'm loving it!",place: .move(dx:145,dy:100))
        let destination = "/var/folders/bm/c45r8p1n3mj6qnz5r79866vr0000gn/T/Madshot/1519937031137_shot.png"
        let img = Image(src: destination)
        let group = Group(contents: [text,img], place: .move(dx: 20,dy:75))
        super.init(node: group, coder: aDecoder)
    }

**Comment by ystrot** [comment]
I recommend you to try following:
* Set image width/height
* Debug Macaw code and make sure that `Image.image()` method load your image correctly

Hope it will help.

**Comment by ystrot** [comment]
Looks like you're trying to load image by path while `Image(src:)` loads image by name. You may use the following code instead:
```
let img = NSImage(byReferencingFile: destination).image()
```

**Comment by DouglasGLewis** [comment]
Yes that is it. Thank you so much  @ystrot . :)
