### ISSUE TITLE
loading tools

### ISSUE THREAD

**Issue by DouglasGLewis** [exyte/Macaw#282]
All of the example that I've seen add tools like Circle for example in the overriden init function. That's fine but I'm trying to add a tool to a MacawView from a normal button click. I'm just not getting it. I keep looking for a view.addtool method or something similar.  How does one add a circle for instance to a view. I don't need to know how to create the Circle. I get that. It's just adding it and displaying it via user interaction from a normal button or menu click.

**Comment by DouglasGLewis** [comment]
Is this done within the node?

**Comment by ystrot** [comment]
If you want to change content of your view completely, you can just set `view.node = newContent`. If you want to change some part of a scene on click, just change it, Macaw handle all changes. For example:

```swift
required init?(coder aDecoder: NSCoder) {
	root = Group(...)
	super.init(node: root, coder: aDecoder)
}

...
func onClick() {
	root.contents = [...]
}
```

**Comment by DouglasGLewis** [comment]
Once again this gave me enough to get it done. Thank you
