### ISSUE TITLE
Android implementation

### ISSUE THREAD

**Issue by deberle** [exyte/Macaw#286]
I love it! 
Do you also have (or plan) an Android implementation? 
For everyone i know, dealing with the "other" platform is the biggest time & fun killer when "converting designs into native views"!

**Comment by ystrot** [comment]
Thanks! And sorry for late response. It will be definitely the great project to have something similar on Android. However our team don't work with Android much, so we're not planning to work on this in the nearest time. But would be great to see someone working on this 😊
