### ISSUE TITLE
[Support] Programmatic use

### ISSUE THREAD

**Issue by rudedogg** [exyte/Macaw#297]
My goal is to render an SVG icon in a `UICollectionViewCell` without storyboards. I tried using `SVGView`, but it seems to ignore the `contentMode` property.

I found an [issue](https://github.com/exyte/Macaw/pull/269#issuecomment-361860020) where it's noted that `SVGView` is meant for storyboard use, so I switched to using `MacawView` instead.

Here's my basic code:
```swift
  private var iconView: MacawView = {
    let view = MacawView(frame: .zero)
    view.contentMode = .center
    view.backgroundColor = UIColor.white
    return view
  }()
```

Where the cell is configured:
```swift
    iconView.node = try! SVGParser.parse(text: String(data: pageTemplate.icon!, encoding: .utf8)!)
    iconView.contentMode = .center
```

This loads the SVG, but contentMode doesn't work. What is the preferred way to achieve this? Should I create a subclass of `MacawView`, and override the `contentMode` code [as suggested](https://github.com/exyte/Macaw/pull/269#issuecomment-363001689)?

I started going that route, but ran into `'bounds' is inaccessible due to 'internal' protection level` on `SVGNode` when I copied over `SVGView.swift` (see https://github.com/exyte/Macaw/blob/master/Source/svg/SVGView.swift#L56) as a starting point.

**Comment by ystrot** [comment]
Hi Austin,

In theory, you should be able to use `SVGView` with `contentMode`, however there is a bug. Anyway, we are planning to finish a big change in the nearest time which allows you to use content mode on `MacawView`.  I'll let you know when this change will be in the master.

**Comment by rudedogg** [comment]
Thanks @ystrot!
