### ISSUE TITLE
Simple arrow

### ISSUE THREAD

**Issue by DouglasGLewis** [exyte/Macaw#304]
I'm looking for a way to draw a simple arrow instead of a Line.

**Comment by ystrot** [comment]
Macaw just gives you a set of primitives which allows you to draw anything you like. For example, here is the sample which draw a simple arrow: https://github.com/exyte/Macaw/blob/master/Example/Example/Examples/Morphing/MorphingView.swift#L18

**Comment by DouglasGLewis** [comment]
Thanks
