### ISSUE TITLE
Rotating line rather than moving with mouse

### ISSUE THREAD

**Issue by DouglasGLewis** [exyte/Macaw#308]
I created a Macaw Line within a Shape and move the line (Shape) in the onPan method line.place.move(dx: event.dx, dy: event.dy). This works great but I would like to rotate the line rather than move it if it is selected near the end of the line. I've played with place.rotate but nothing is working for me. Do you have an example of rotating with the mouse?

Thanks for all of your prior help.

**Comment by ystrot** [comment]
Hi Douglas,

I'm sorry for late response. If it's still the case, I would recommend you to change `shape.form` to the new `Line` according to your mouse coordinates. This will be easier then calculating rotation angle.

**Comment by ystrot** [comment]
Closing this issue. Please open another one if you have other questions.
