### ISSUE TITLE
Not show Arc (A), Qubic Beizer (Q) from SVG Path

### ISSUE THREAD

**Issue by solidarik** [exyte/Macaw#345]
Incorrect drawing a path which contains Arc or Qubic Beizer elements.

Example:
https://shkspr.mobi/svg/calendar.svg

I saved this svg in file calend.svg and try get image from MacawView, just like in Tiger example
```
let calend = try! SVGParser.parse(path: "calend")
let group = Group(contents: [
            calend,            
            text
            ], place: .move(dx: 100 / 2, dy: 150))
```

The example include A element in path, but Macaw showed this incorrectly:
<path xmlns="http://www.w3.org/2000/svg" d="M484 0h-47c2 4 4 9 4 14a28 28 0 1 1-53-14H124c3 4 4 9 4 14A28 28 0 1 1 75 0H28C13 0 0 13 0 28v157h512V28c0-15-13-28-28-28z" fill="#dd2f45"/>

<img width="290" alt="screen shot 2018-05-04 at 22 15 44" src="https://user-images.githubusercontent.com/1526149/39641754-cac7bbee-4fe8-11e8-8f3c-790a474c1f9d.png">

**Comment by ystrot** [comment]
Hi Ildar,

This example works fine in the master version. So you can switch to the master branch or wait for the stable 0.9.2 release.

**Comment by solidarik** [comment]
Thanks! I confirm in the master version Arc is processed correctly.
