### ISSUE TITLE
Fill color disappears if there is stroke color

### ISSUE THREAD

**Issue by f3dm76** [exyte/Macaw#347]
The following text is white with black border
```
    <g fill="blue" stroke="black">
        <text x="160" y="40">Filler Text</text>
    </g>
```

**Comment by danielcmm** [comment]
Im also having this problem... unable to add a border/stroke to a Text object because when we set the stroke the fill color disappears.

Any news on this? Thanks!

**Comment by ystrot** [comment]
Thank you for pointing to this issue! We've also fixed another one when you couldn't use `stroke` without `fill`.
