### ISSUE TITLE
How to "Shake" group ?

### ISSUE THREAD

**Issue by LeChatNoir69** [exyte/Macaw#370]
Hi there, 

I'm making some tests on this framework and got questions :

1. How can I easyly make a "shake" animation. Let say rotate left for some degrees and rotate back to initial position then rotate right for some degrees and repeat 3 or 4 times ? How can one achieve that ?

2.Can I stroke an entire group of different shape ? In this group, there are others groups and / or shapes

Thank you !

**Comment by ystrot** [comment]
1. There are a lot of different ways to make shake animation. In general, you can use something like this:
```swift
let shape = Rect(x: 100, y: 100, w: 100, h: 100).fill(with: Color.blue)
shape.onTap { e in
    // shape center
    let cx = 150.0
    let cy = 150.0
    // shake angle
    let angle = Double.pi / 12
    // one shake time in seconds
    let time = 0.08
    // number of shakes
    let moves = 10

    shape.placeVar.animate(angle: angle, x: cx, y: cy, during: time / 2)
    var delay = time / 2
    for i in 0...moves {
        let direction = Double((i % 2) * 2 - 1)
        shape.placeVar.animate(angle: direction * angle, x: cx, y: cy, during: time, delay: delay)
        delay += time
    }
    shape.placeVar.animate(angle: 0, x: cx, y: cy, during: time / 2, delay: delay)
}
```

That's how it works:
<img src="https://i.imgur.com/a54XG16.gif"/>

You can customize parameters or find another implementation and port it to Macaw.

2. Unfortunately Macaw doesn't allow you to do it out of the box. You need to define such a `Path` yourself and stroke it.

**Comment by LeChatNoir69** [comment]
Ok thank you.

Strange behaviour : when svg simply rendered, groups are little blur. And when animation starts, Shape are very clean and precise. No more blur.

Any idea why ?

**Comment by LeChatNoir69** [comment]
Look at that sceenshot. Number 33 shape is animated. It appears really clean.
Number 34 is not animated. It appears blur.

I'd like all my shape to be as clear as number 33.

The SVGView is in a scrollView and I'm zooming for that screenshot. The SVGView is in mode "AspectFit". 

Thank you for your help.

![macaw](https://user-images.githubusercontent.com/1202490/40702172-1cb680be-63e1-11e8-987d-9ac6e15c15e2.png)

**Comment by ystrot** [comment]
That's probably because you need to force your view to redraw once you zoom in. Try to call `setNeedsDisplay()` on your SVGView after zooming.

**Comment by LeChatNoir69** [comment]
I just give it a try : not better :(

I did it in the scrollViewDidEndScroll. The method is called but not better.

Guillaume

**Comment by LeChatNoir69** [comment]
And more than that : at the end of the animation, the animated shape come back to blur.
Any idea ?

**Comment by ystrot** [comment]
Closing this issue, because original question was addressed. If you have other questions please open another ticket. There are several opened issues related to scrolling.
