### ISSUE TITLE
Can't get svgNode property in SVGView

### ISSUE THREAD

**Issue by 008v** [exyte/Macaw#405]
`  
  fileprivate var svgNode: Node?
fileprivate func parseSVG() {
    svgNode = try? SVGParser.parse(path: fileName ?? "")
  }
`

I'm going to add onTap callback for each child node of svgNode before the render() method executes.

**Comment by f3dm76** [comment]
MacawView's node property is public, is it possible in your case to use MacawView instead of SVGView?

**Comment by 008v** [comment]
But MacawView does not support contentMode.

**Comment by f3dm76** [comment]
It does in the master branch, consider switching to it. It will be included in the next release. Sorry for the inconvenience.

**Comment by 008v** [comment]
Another question: 
`    override func viewDidLoad() {
        super.viewDidLoad()
        
        scrollView = UIScrollView.init(frame: view.bounds)
        mySVGView = MySVGView.init(f: "zen", frame: scrollView.bounds) // extends from MacawView Class
        mySVGView.contentMode = .scaleAspectFit
        scrollView.addSubview(mySVGView)
        scrollView.contentSize = mySVGView.bounds.size
        scrollView.maximumZoomScale = 10.0
        scrollView.minimumZoomScale = 1.0
        scrollView.delegate = self
        view.addSubview(scrollView)
    }
    
    func viewForZooming(in scrollView: UIScrollView) -> UIView? {
        return mySVGView
    }`

The enlarged image is blurred. Why ?

**Comment by amarunko** [comment]
Hi, @008v, thank you for provided example. I think as hotfix you can redraw view on the zooming. For example in your case (here I'm using clear macaw view without overloading layoutSubviews):

`func scrollViewDidEndZooming(_ scrollView: UIScrollView, with view: UIView?, atScale scale: CGFloat) {
    
        if let recognizer = scrollView.pinchGestureRecognizer {
            let location = recognizer.location(in: scrollView)
            let scale = recognizer.scale
            let rect = zoomRect(scale: scale, center: location)
            mySVGView.removeFromSuperview()
            mySVGView = MySVGView.init(f: "zen", frame: rect)
            mySVGView.contentMode = .scaleAspectFit
            scrollView.addSubview(mySVGView)
        }
    }
    
    func zoomRect(scale: CGFloat, center: CGPoint) -> CGRect {
        var zoomRect = CGRect.zero
        
        zoomRect.size.height = mySVGView.frame.size.height / scale
        zoomRect.size.width  = mySVGView.frame.size.width  / scale
        
        // choose an origin so as to get the right center.
        zoomRect.origin.x    = center.x - (zoomRect.size.width  / 2.0)
        zoomRect.origin.y    = center.y - (zoomRect.size.height / 2.0)
        
        return zoomRect
    }`

It is the small hack and not the best solution; We will try to find a better solution and resolve this problem automatically by Macaw.

**Comment by 008v** [comment]
This is not an elegant solution. If the size of SVGImage object is too large, memory will overflow.

Can you solve this problem with node.place?

**Comment by amarunko** [comment]
Node.place doesn't change UIView frame - you should additionally control frame. We will try to resolve this problem soon.

**Comment by ystrot** [comment]
Looks like this is an outdated issue. MacawView has accessible node property and there is also zooming functionality. So closing this issue.
