### ISSUE TITLE
Parse SVG Falseness 

### ISSUE THREAD

**Issue by Junyi1227** [exyte/Macaw#412]
I parsed svg file. The parse reason is falseness . 
```
class SubwayView: MacawView {
    required init?(coder aDecoder: NSCoder) {
        super.init(node: Group(contents: []), coder: aDecoder)
        let long = try! SVGParser.parse(path: "boy_1_long") as! Group
        
        self.node = long
    }
}
```    
[svg files & errorimage](https://drive.google.com/open?id=1KmDS6hB6FnP7O85cgpgKU9VqN1j_yGhx)

**Comment by ystrot** [comment]
Could you please share access to your files?

**Comment by Junyi1227** [comment]
https://drive.google.com/drive/folders/1RFoyvRZ4naKSFX8BOiMqLHhyH3bxikeu?usp=sharing

**Comment by Junyi1227** [comment]
By the way, could I control SVG image animation by slider?
hmmm...
ex:
https://drive.google.com/file/d/192kg0g41s_mh7XEfwa__zhZqgJ6WBZoY/view?usp=sharing

**Comment by ystrot** [comment]
You can switch to the master branch version, it will render your SVG correctly. As for animation, Macaw currently doesn't support SVG animation. So you need to imitate this effect on your own by changing the Macaw model or using morphing animation: https://github.com/exyte/Macaw/wiki/Morphing-animation.

Also you can't control animation, but you can calculate the state based on your slider value and apply these changes to the model.

**Comment by Junyi1227** [comment]
OK... I try it.
Thank you ~
