### ISSUE TITLE
SVG False After Animation

### ISSUE THREAD

**Issue by Junyi1227** [exyte/Macaw#418]
I Parse SVG, it's right.
But,after animation,it's false.
up, it's animation.
down. only show.

code:
![image](https://user-images.githubusercontent.com/3872668/41266713-d094cb6a-6e2a-11e8-9742-a4219d6bba7a.png)

PODS:
  - Macaw (0.9.2):
    - SWXMLHash
  - SWXMLHash (4.7.0)

svg image
[svg.zip](https://github.com/exyte/Macaw/files/2092331/svg.zip)

result
![2018-06-12 10 18 55](https://user-images.githubusercontent.com/3872668/41266654-7b3ca566-6e2a-11e8-938a-ff4fe9935703.png)

Thank you

**Comment by ystrot** [comment]
Reproduced. Looks like a bug, will try to fix it in this milestone.
