### ISSUE TITLE
node.place transform is wrong ! ! !

### ISSUE THREAD

**Issue by 008v** [exyte/Macaw#420]
Here is my project.

https://github.com/008v/SVGChangeColor.git
commit ffe98d1bd5e4630ba903c5a39fb1bb374f07faaf

Each time you click in the image, the image will moves 100 pixels to the right. But you're actually moving the SVG original image size, not based on the actual pixels of the screen.

If I want to move with the actual pixels of the screen, what do I do?

**Comment by ystrot** [comment]
Hi Qin,

What do you mean by "actual pixels of the screen" and why is it different from SVG coordinate system? If you apply some kind of scaling then you need to consider it when you moving your image (move to 100 * <scaling factor>).

**Comment by 008v** [comment]
let shape = Shape(form: Rect(x: 0, y: 100, w: 100, h: 100),
                          fill: Color(val: 0xfcc07c),
                          stroke: Stroke(fill: Color(val: 0xff9e4f), width: 2))
        let macawView = MacawView.init(node: shape, frame: view.bounds)
        macawView.contentMode = .scaleAspectFit
        view.addSubview(macawView)
        macawView.node.place = macawView.node.place.move(dx: 100, dy: 0)

I'm sorry my English is not very good.
The above code demonstrates this bug. 
In .scaleAspectFit mode, the distance node moves is not what I expected. I want it to move 100 pixels to the right. But it actually moves the screen width.

**Comment by ystrot** [comment]
It's a bad practice to set up content mode and then change place of the root node, because content mode actually change your node's place automatically. If you want to control your root's place on your own you need to make scale aspect fit manually:

```swift
let rect = Rect(x: 0, y: 0, w: 100, h: 100)
let shape = Shape(form: rect,
                      fill: Color(val: 0xfcc07c),
                      stroke: Stroke(fill: Color(val: 0xff9e4f), width: 2))
let macawView = MacawView.init(node: shape, frame: view.bounds)
view.addSubview(macawView)
let viewSize = macawView.bounds.size.toMacaw()
shape.place = Transform
        // move shape to 100 points right in the view coordinates BEFORE scale
        .move(dx: 100, dy: 0)
        // scale aspect fit
        .scale(sx: viewSize.w / rect.w, sy: viewSize.h / rect.h)
```

**Comment by 008v** [comment]
Can you consider changing back to the previous commit? I'm using the commit '10996a4' now. But this commit does not implement the contentMode.

**Comment by ystrot** [comment]
It's better to use the latest version cause there are a lot of fixes. Anyway the sample above should works fine on every version because it doesn't use `contentMode`.

**Comment by 008v** [comment]
All right. Everything is based on Transform. Let me try.
