### ISSUE TITLE
How Not To Enlarge SVG,After SVG Animate Complete

### ISSUE THREAD

**Issue by Junyi1227** [exyte/Macaw#425]
![f74dn-nicwn](https://user-images.githubusercontent.com/3872668/41462989-68d4f3ca-70c7-11e8-8141-cf14bfac4287.gif)

Change slider to animate. 
How not to enlarge SVG,after SVG animate complete

![image](https://user-images.githubusercontent.com/3872668/41463260-64b1a134-70c8-11e8-9c5b-da5462b44b85.png)

**Comment by f3dm76** [comment]
Fixed in the latest release (0.9.4), you are welcome to check it out.
