### ISSUE TITLE
How to scale SVGView

### ISSUE THREAD

**Issue by LeChatNoir69** [exyte/Macaw#426]
Hi,

Here is the explanation :
=> Got an UIScrollview with fixed Height
=> Got a jpg picture in that scrollview. I compute ratio so the picture fit in height and user can scroll horizontaly to view the all width
=> Got a SVGView over it with same size. ContentMode = ScaleToFill. 

Unfortunately, the svg inside is not correctly scaled.

Does I have to scale it manually ? How ?

Here is the code for UIImageView sizing : 

```
        let viewHeight = self.graphicSv.bounds.size.height
        let imageWidth = (cragImage?.size.width)! / (cragImage?.size.height)! * viewHeight
        self.cragPictureWidth.constant = imageWidth
        self.cragPictureHeight.constant = viewHeight
```

**Comment by 008v** [comment]
scrollView.addSubview(imgView)
scrollView.contentSize = imgView.bounds.size

**Comment by 008v** [comment]
You can add a dummy view for scrollView.  And the color of dummy view is clear color. You could get the contentOffset and scale in scrollViewDidScroll method. So you could change node.place of MacawView to scale or move it.

**Comment by 008v** [comment]
Never try to change the frame size of MacawView to get a clear image. Memory will warn.

**Comment by ystrot** [comment]
Shouldn't be an issue anymore, so closing it.
