### ISSUE TITLE
SVG render speed is very slow

### ISSUE THREAD

**Issue by 008v** [exyte/Macaw#428]
https://github.com/008v/SVGChangeColor/tree/scrollView
branch: scrollView

Above is a project I wrote to change the color of SVG.
It scales based on the UIScollview.
When you zoom in, the frame of the MacawView will change.
Tap on a path in SVG will fill with the gradient.
Unfortunately, the larger the frame, the slower the rendering.
Is there any good way to optimize the rendering speed?

**Comment by ystrot** [comment]
`MacawView` has built-in zoom feature with good performance which should resolve this issue.
