### ISSUE TITLE
Unsupported locus (for typeof Path)

### ISSUE THREAD

**Issue by Lapinou42** [exyte/Macaw#432]
Hello, 

I got this fatal error from Locus+ToPath.swift line 73.
I put some break point and find that "self" is kind of "Path" class. 

Is there a workaround to deal with that ? 

Thank you,
Christophe.

**Comment by f3dm76** [comment]
Please provide code you use to achieve the error - svg file or manually created primitives

**Comment by ystrot** [comment]
Please use the latest release version (0.9.2). You can reopen this issue with a sample if it's still reproducible.
