### ISSUE TITLE
Dynamic font size of Text to fit into Shape in MacawView?

### ISSUE THREAD

**Issue by caneh** [exyte/Macaw#433]
Hello,
I am currently trying to figure out how to fit a `Text()` into a `Shape()`/`Rect()` in Macaw. Basically, I want to create multiple buttons (the Shapes) with different labels on each of them (the Texts), similar to Xcode’s UIButton and Label. Problem is, depending on the length of the strings, the text will of course go further than the bounds of the Shape. Manually adjusting the font size for each Text is currently not an option, given that the strings will also be localised into different languages.

Is there a way to “attach” a Text to a Shape/Rect and force a smaller text if it reaches the Shape’s boundaries (just like `mybutton.titleLabel?.adjustsFontSizeToFitWidth = true` for UIButtons)? Maybe even automatically break the text into multiple lines? The Shape’s width/height should always be fixed.

**Comment by ystrot** [comment]
Hi caneh,

Current master version have `bounds` feature. You can call `text.bounds` and calculate the right `place` for your text. You can use master branch or wait for the new release which will be on this week.

**Comment by ystrot** [comment]
`text.bounds` now available in the release version, so closing this issue.
