### ISSUE TITLE
Missing initializer 'init(frame:)' in SVGView makes it unusable with IBDesignable

### ISSUE THREAD

**Issue by edmundmaruhn** [exyte/Macaw#435]
Unfortunately the `SVGView` class lacks of an initializer that is invoked behind the scenes by Xcode when applying _IBDesignable_ marked components. This lets the `IBDesignablesAgentCocoaTouch` agent crash and views do not render properly and breaking that awesome Xcode feature at all.

Please can you add the missing initializer to `SVGView`?

**Comment by ystrot** [comment]
Fixed in the master branch and will be part of the upcoming 0.9.2 release.

**Comment by mrgrauel** [comment]
This causes that `SVGView.init(frame: .zero)` is an ambigious call cause the methode `init(node: frame:)` has an default value for node. To fix this we have to remove the default value for the node.

**Comment by ystrot** [comment]
@mrgrauel looks like you're right. Sad we already released 0.9.2, but fixed this in the master branch.
