### ISSUE TITLE
About this app

### ISSUE THREAD

**Issue by hhoangna** [exyte/Macaw#444]
I want to make an app like this. 
Can you help me?
![687474703a2f2f692e696d6775722e636f6d2f706a6d787244492e676966](https://user-images.githubusercontent.com/26923574/42142506-f38ef9ba-7dd9-11e8-84aa-4e9212a5e5d8.gif)

**Comment by amarunko** [comment]
Feel free to check out our repository with this example - https://github.com/exyte/Macaw-Examples/tree/master/PeriodicTable

**Comment by hhoangna** [comment]
![screen shot 2018-07-03 at 09 18 47](https://user-images.githubusercontent.com/26923574/42195254-255d4514-7ea2-11e8-965f-5be0318c36a8.png)
This is error in PeriodicTable.swift
Please update!!! Thanks

**Comment by amarunko** [comment]
@hhoangna which version of Macaw did you use?

**Comment by hhoangna** [comment]
@amarunko According the pod, the version is 0.9.0

**Comment by ystrot** [comment]
Pod file refer to the latest version: https://github.com/exyte/Macaw-Examples/blob/master/PeriodicTable/Podfile which is 0.9.2. Please update your pod and make “pod install”

**Comment by hhoangna** [comment]
Oh. Thanks! I forgot to check version.
Can we touch up each element to show information of the element which we touched?

**Comment by amarunko** [comment]
Yes, you can add touch events to Node object. You can find examples here: https://github.com/exyte/Macaw/blob/master/Example/Example/Examples/Events/EventsExampleController.swift

**Comment by hhoangna** [comment]
![screen shot 2018-07-03 at 12 07 18](https://user-images.githubusercontent.com/26923574/42199628-a9426410-7eb9-11e8-830e-93bef3cda548.png)
When the element like this. Can we swipe left or right to make them rotate in the same direction as rotating the globe?

**Comment by amarunko** [comment]
Yes, you can handle swipe gesture on view and do animated transformation using place variable of Node or place variable of root node/group of nodes.

**Comment by hhoangna** [comment]
Could you upgrade that function in PeriodicTable? I'm a newbie, so i don't know how to handle that!
Thanks! @amarunko

**Comment by ystrot** [comment]
Hi Huy,

You need to understand event system and affine transformation to complete your task and it's more about basic iOS/programming skills. Macaw community is not that big, so you'll unlikely find someone on the Github issues which can help you with this. I recommend you to use other platforms like Stackoverflow having awards system which motivates people to help each other. Also please feel free to read https://github.com/exyte/Macaw/wiki/Getting-started tutorial to learn more about Macaw.

**Comment by hhoangna** [comment]
Thanks you so much <3
