### ISSUE TITLE
Problem in code completion 

### ISSUE THREAD

**Issue by cs14rendra** [exyte/Macaw#447]
Xcode is not auto completing code when I am using Macaw library. so its hard to code. please find below image to see the problem.
->>: https://i.imgur.com/aztb1cX.png

Xcode version :  9.2 (9C40b)
Macaw : "0.9.2"

Thank you!

**Comment by ystrot** [comment]
Hi Surendra,

Code completion issues relate to Xcode. So please feel free to file an issue to Apple's bug tracker.

**Comment by cs14rendra** [comment]
May be not,
With & without other third party lib code completion is working fine. I created many projects and installed macaw with pod but got same problem with every project.

**Comment by amarunko** [comment]
Hi, @cs14rendra, is your project contains IBDesignable?

**Comment by cs14rendra** [comment]
Hi @amarunko ,
NO. I am not using @IBdesinable and my project have only Macaw lib.
I will update my Xcode and check again. Thank you!

**Comment by ystrot** [comment]
Closing it, because this is Xcode issue.
