### ISSUE TITLE
Typo in Rect.center()?

### ISSUE THREAD

**Issue by beta** [exyte/Macaw#449]
https://github.com/exyte/Macaw/blob/master/Source/model/geom2d/Rect.swift#L35

```swift
open class Rect : Locus {
    ...
    open func center() -> Point {
        return Point(x: x + w / 2, y: y + w / 2)
    }
    ...
}
```

IMHO the second param should be `y + h / 2`. Is this a typo?

**Comment by ystrot** [comment]
Thanks for a good catch! Fixed in the master branch.
