### ISSUE TITLE
How to display SVG from URL?

### ISSUE THREAD

**Issue by edopelawi** [exyte/Macaw#455]
Dear all,

I have tried Macaw's SVGView for drawing SVG in UITableViewCell, and the performance has been very good! Problem is, SVGView's API only allows loading SVG file from the resources bundle, and I want it to load an SVG from URL.

From what I know, iOS' resources bundle is read-only, so I need to store the SVG files somewhere else. Is there any way for Macaw's SVGView to load file outside of the resources bundle?

Thanks in advance!

**Comment by amarunko** [comment]
Hello, @edopelawi, for the fast solution you can use the method "func parse(text: String)" from SVGParser for parsing SVG string content loaded from the network. You got Node after parsing which you can use in MacawView.

**Comment by edopelawi** [comment]
@amarunko, thank you for the reply! I'll try that out!

**Comment by edopelawi** [comment]
@amarunko, quick question - the code you provided above will block the main thread, no? What if I want to download the SVG in the background thread, and then load the "node" later on?

**Comment by amarunko** [comment]
it is just an example, of course, you can use URLSession or wrappers (Moya, Alamofire, etc.) for downloading content in the background and then update node with downloaded and parsed SVG.

**Comment by edopelawi** [comment]
You're right! I just tried to parse the SVG directly and update the MacawView's node, and it worked correctly!

I'll close this issue then - thank you for the help, @amarunko ! 👍

**Comment by luminkhant** [comment]
@edopelawi  Could you please show me your sample code to load svg from URL.

**Comment by edopelawi** [comment]
Hey @luminkhant , sorry for the late reply. I didn't have access to the code anymore... my apologies!

**Comment by luminkhant** [comment]
Its ok. I handled it by myself. Thanks @edopelawi
