### ISSUE TITLE
Crash when rendering SVG in Node.swift, line 319

### ISSUE THREAD

**Issue by edopelawi** [exyte/Macaw#458]
Dear all,

I'm currently using Macaw version 0.9.2, and got intermittent crashes when rendering SVG string. It's intermittent and I can't reproduce it yet, but Crashlytics' report says it came from `Node.init(place:opaque:opacity:clip:mask:effect:visible:tag:)`  method in Node.swift, line 319. Anyone ever faced this issue before?

I'll update this issue should I able to reproduce the crash consistently.

Thanks in advance!

**Comment by edopelawi** [comment]
Just got one intermittent crash in the simulator with an error of `EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)`. The code halts in Node.swift line 319, here's the code:

`Node.map.setObject(self, forKey: self.id as NSString)`

The thread where the crash happened was `com.apple.root.default-qos`, and looking at the instances involved above, the `self`, `self.id`, or `Node.map` might be a `nil`.

After further digging, the `Node.map` is an `NSMapTable`... is it suitable for multi-threaded operations? Should I do the rendering in the main thread for safety reasons?

**Comment by amarunko** [comment]
If you use MacawView, you always should do rendering in the main thread

**Comment by edopelawi** [comment]
@amarunko thanks for the response. Upon further inspection, turns out the crashes were caused by invalid SVG -  when downloaded from the internet, the String still has escape characters for the double-quotes (\"). Sanitizing the input string from escape characters seems to be the solution - will let you guys know later.

**Comment by Beniamiiin** [comment]
@amarunko is it possible to render `SVG` to `UIImage` in the background thread?

**Comment by cHaLkdusT** [comment]
Hi @edopelawi,

Are there any updates on this issue? If you were able to fix this on your end, kindly close this issue.

Thanks,

**Comment by edopelawi** [comment]
@cHaLkdusT not yet. It seems there are some issues in Node's threading...

**Comment by edopelawi** [comment]
Fixed by using the `SVGParser` in the main thread. I thought parsing SVG could be moved to the background thread and setting the node in the main thread... Thanks, folks!

**Comment by ystrot** [comment]
Solution was found, so Closing this one.
