### ISSUE TITLE
Shapes not supported when rendering an svg file programatically?

### ISSUE THREAD

**Issue by returnzer0** [exyte/Macaw#459]
Hi, 

I am using SVGView to try and render this svg shape but I get all these errors in my log.

SVG parsing error. Shape filter not supported
SVG parsing error. Shape feOffset not supported
SVG parsing error. Shape feColorMatrix not supported
SVG parsing error. Shape feOffset not supported
SVG parsing error. Shape feGaussianBlur not supported
SVG parsing error. Shape feColorMatrix not supported
SVG parsing error. Shape feMorphology not supported
SVG parsing error. Shape feOffset not supported
SVG parsing error. Shape feColorMatrix not supported
SVG parsing error. Shape feMerge not supported
SVG parsing error. Shape feOffset not supported
SVG parsing error. Shape feColorMatrix not supported
SVG parsing error. Shape feOffset not supported
SVG parsing error. Shape feGaussianBlur not supported
SVG parsing error. Shape feColorMatrix not supported
SVG parsing error. Shape feMorphology not supported
SVG parsing error. Shape feOffset not supported
SVG parsing error. Shape feColorMatrix not supported
SVG parsing error. Shape feMerge not supported

Here is my code:

`let node = try! SVGParser.parse(bundle: Bundle.main, path: "routing", ofType: "svg")`
`let svgView = SVGView.init(node: node, frame: CGRect.init(x: 0, y: 100, width: 300, height: 150))`
`svgView.contentMode = .scaleAspectFit`
`svgView.backgroundColor = .white`
`view.addSubview(svgView)`

Here is my file, please change the extension to .svg as github will not allow .svg uploads.
[routing.txt](https://github.com/exyte/Macaw/files/2294748/routing.txt)

Any ideas to why this is? I searched these up but didn't get too far.

Thanks

**Comment by amarunko** [comment]
Hi, @returnzer0, first of all - attached SVG is broken. Secondly - Macaw library doesn't support for now features above (log is informing about it), we will try to add this features as soon as possible.

Just for the experiment - SVG regenerated by Sketch - parsed by Macaw pretty fine.

Regenerated SVG - [routing.txt](https://github.com/exyte/Macaw/files/2295878/routing.txt)

**Comment by returnzer0** [comment]
Wow, i didn't realize that. My apologies, thank you so much!
