### ISSUE TITLE
Animation of fill var not happening after the first tap

### ISSUE THREAD

**Issue by aure** [exyte/Macaw#462]
When I add tap to a group, the first time I see the nice background animation, but afterwards I don't see anything.  I do get the "tap!" printed to the log, so I know the tap is being registered.  I'd be happy to submit a pull request if you can give me a hint where to look.

        group.onTap { _ in
            print("tap!")
            self.valueBG.fillVar.animate(from: Color.white, to: Color(val: 0x333333), during: 0.1)
        }

**Comment by f3dm76** [comment]
Thank you very much for pointing out this flaw. We will work on that in the nearest future and let you know as soon as it's done.

**Comment by f3dm76** [comment]
aure, issue is fixed in the master branch, welcome to check it out. Thanks again!

**Comment by aure** [comment]
Thanks I'll give it a try!
