### ISSUE TITLE
Multi svg in a svg root parent

### ISSUE THREAD

**Issue by tanphamanhh** [exyte/Macaw#464]
I have a svg file. in this root svg, i have some svg child like that:
```
<svg>
<svg></svg>
<svg></svg>
...
</svg>
```
when i show this file using SVGView. it did show like i expected.
How can i use that library to view svg file like this?

**Comment by tanphamanhh** [comment]
ok, i'll try it
hope this feature will be availabe soon :)

**Comment by f3dm76** [comment]
Duplicate #344
