### ISSUE TITLE
Getting a UIImage from the SVG file on a background thread without using a MacawView.

### ISSUE THREAD

**Issue by BrettAtMangoHealth** [exyte/Macaw#468]
Greetings, 

Thank you for the work provided in the Macaw library. 

Our team is trying to do something similar to [this open PR #382](https://github.com/exyte/Macaw/pull/382). We are trying to collect a UIImage from the SVG file on a background thread. Attempting to use the code snippet provided by @ystrot, the resulting image is always blank or empty. I was wondering if there is a solution to this without using MacawViews. 

Thank you for your time. If there needs to be any clarification, please ask.

**Comment by szuwest** [comment]
I hava the same problem,too
I found UIImageExtensions.swift in source code at github, but not in pod sources.

**Comment by ystrot** [comment]
`UIImageExtensions` is part of the [Eugene's PR](https://github.com/exyte/Macaw/pull/382), so it's not in the pod.

For now you can use following sample: https://github.com/exyte/Macaw/pull/382#issuecomment-393422770, but it doesn't work in background thread. To make it possible in background we need to change our rendering system. So we keeping this feature in mind and will implement it once it can be possible.

**Comment by dreampiggy** [comment]
So....Does this means my dream of using your awesome SVG engine to polish our SVG coder plugin  [SDWebImageSVGCoder](https://github.com/SDWebImage/SDWebImageSVGCoder) is impossible 😅 

Currentlly we have to use [SVGKit](https://github.com/SVGKit/SVGKit), which contains some bug for rendering the modern SVG files, but at least works for background rendering mode. That framework seems lack of matainer.

**Comment by ystrot** [comment]
Hey dreampiggy. Thank you for the kind words! This task is one of the first in our roadmap, so I hope your dream will come true in the nearest time 😊

**Comment by ystrot** [comment]
Hey guys! Can anybody provide a sample showing that `MacawView` doesn't work in a background thread? I was trying to do it this way:
```Swift
    override func viewDidLoad() {
        super.viewDidLoad()

        DispatchQueue.global(qos: .background).async {
            let image = self.svgToImage(resourceName: "logo", size: CGSize(width: 100, height: 100))
            DispatchQueue.main.async {
                self.view!.backgroundColor = UIColor(patternImage: image)
            }
        }
    }

    func svgToImage(resourceName: String, size: CGSize) -> UIImage {
        let rootNode = try! SVGParser.parse(resource: resourceName)
        let macawView = MacawView(node: rootNode, frame:CGRect(origin: CGPoint.zero, size: size))
        UIGraphicsBeginImageContext(size)
        macawView.layer.render(in: UIGraphicsGetCurrentContext()!)
        let img =  UIGraphicsGetImageFromCurrentImageContext();
        UIGraphicsEndImageContext();
        return img!
    }
```
But it works fine for me.

**Comment by szuwest** [comment]
it is not safe.sometime it is ok,sometime it will crash

Yuri Strot <notifications@github.com>于2018年10月31日 周三下午8:38写道：

**Comment by ystrot** [comment]
Now you can convert any node to a UIImage using following method:
```Swift
try! SVGParser.parse(resource: resourceName).toNativeImage(size: imageSize)
```

You can also specify [content layout](https://github.com/exyte/Macaw/wiki/Understanding-MacawView-content-layout) as an argument to align a Node/SVG.
