### ISSUE TITLE
Fatal error with fills on animation

### ISSUE THREAD

**Issue by aure** [exyte/Macaw#469]
I believe this is related to the fix for this issue:

https://github.com/exyte/Macaw/issues/462#issuecomment-415323944

But since I can't reopen that issue, I'm creating a new issue, I hope that is okay.

**Comment by f3dm76** [comment]
Of course it's ok, thanks! Recreated, fixed, please try again

**Comment by aure** [comment]
The fatal error is fixed, but the nature of some of animation is affected I think, in a non-expected way.  I will come up with some example code and submit another issue.  Thanks for your diligence.
