### ISSUE TITLE
Custom.otf fonts not supported

### ISSUE THREAD

**Issue by ElyDantas** [exyte/Macaw#473]
Sadly i can't load my custom otf font that's tailored for my project inside the graphs i'm creating with Macaw.

```
private let numberFont = Font(name: "Titillium-Light", size: 16) // Not working
private let numberFont = Font(name: "Serif", size: 16) // Working
```

**Comment by godexsoft** [comment]
I happened to have the same exact issue with ttf fonts right now. I have found the solution to my problem and i encourage you to try it with your issue too! 
Check this https://github.com/exyte/Macaw/issues/474

Cheers,
Alex

**Comment by ystrot** [comment]
This issue fixed in the master branch and will be part of 0.9.4 release.
