### ISSUE TITLE
Swift 4, Xcode 10 Compilation

### ISSUE THREAD

**Issue by Zachapata** [exyte/Macaw#481]
Hello! I've added `pod 'Macaw', '0.9.2'` to my Podfile, but my project is not compiling. It's giving a bunch of errors (32 errors) regarding renamed/removed APIs between Swift versions. I see there was some work for Swift 4.2 compatibility recently. Is that available in Macaw 0.9.2? My apologies if I'm doing something terribly wrong here. I'm fairly new to CocoaPods.

Error Example
<img width="2030" alt="screen shot 2018-09-27 at 5 03 41 pm" src="https://user-images.githubusercontent.com/25736512/46180834-87338f00-c277-11e8-85e8-84951e57eab3.png">

Config Showing 0.9.2
<img width="2028" alt="screen shot 2018-09-27 at 5 05 59 pm" src="https://user-images.githubusercontent.com/25736512/46180852-a3373080-c277-11e8-9598-d2fe6dd749b0.png">

**Comment by amarunko** [comment]
Hi, @Zachapata, we will provide new release, including iOS 12 support soon. For now, you can use changes from the master branch directly. How to work with cocoapods you can find [here](https://guides.cocoapods.org/using/the-podfile.html). For Macaw case it will be something like:

`pod 'Macaw', :git => 'https://github.com/exyte/Macaw.git', :branch => 'master'

**Comment by ystrot** [comment]
`0.9.3` version released with Swift 4.2 support.
