### ISSUE TITLE
Group.deinit func seems to break tap handlers nondeterministically

### ISSUE THREAD

**Issue by DanielMahu** [exyte/Macaw#484]
My test project app is displaying a graph and relying on a lot of onTap handlers added to groups in the scene. I discovered that taps don't work well with the more recent versions of Macaw from master, and narrowed this down to a single change in the Group class, when a deinit function was added:
https://github.com/exyte/Macaw/commit/9f71e7d1bff64971bbb5209a41cc3796e0d87bde#diff-ea5f122ae7f77fb3c9d5e4aefb7a0c0aR43

When I comment out the deinit() function, my app works fine, but when I leave it in the onTap and onPinch handlers sometimes do not get called. Here is a screen recording showing this:
https://www.youtube.com/watch?v=uCvkC1uKxMY

**Comment by DanielMahu** [comment]
+@amarunko who authored the commit.

**Comment by amarunko** [comment]
Hello, @DanielMahu, I removed the unneeded manual removing a group from the nodes map. You can find the last changes in master. I hope we will provide release with these changes this week.

**Comment by DanielMahu** [comment]
Wonderful, thank you! My project works with the version from head.
