### ISSUE TITLE
Sharing Node instance across different SVGViews causes infinite loop

### ISSUE THREAD

**Issue by lubiluk** [exyte/Macaw#488]
Hi, I use Macaw (great library) in such a way that I download SVG files from the internet to memory cache, turn them into Macaw Nodes, manipulate them to alter their colors and then use them as icons in a table view.

### The issue
I noticed that when one Node instance appears in more than one SVGView the main thread enters an infinite loop (somewhere in drawRect).

### Discussion
It looks like Macaw doesn't really like using Nodes directly. For instance, once a node is set on MacawView, there's no way to nil it out, so I had to use an awkward construction like this:
```
if let icon = model.icon {
    titleCell.iconSvgView.node = icon
} else {
    titleCell.iconSvgView.fileName = nil
}
```

I can of course try to redesign my code so it saves images on the disk but isn't it worth discussing why a flow that would be typical for UIImage does not work for Macaw.Node?

**Comment by amarunko** [comment]
Hi, @lubiluk, you can use MacawView instead of SVGView, but get Node from SVGparser:

```swift
open class func parse(path: String, ofType: String = "svg") throws -> Node
```

But avoid of parsing SVG each time, it can take some resources, better cache parsed nodes.

**Comment by amarunko** [comment]
Did you try copying of node for quick fix?

```swift
func copyNode(_ referenceNode: Node) -> Node? {
        let pos = referenceNode.place
        let opaque = referenceNode.opaque
        let visible = referenceNode.visible
        let clip = referenceNode.clip
        let tag = referenceNode.tag

        if let shape = referenceNode as? Shape {
            return Shape(form: shape.form, fill: shape.fill, stroke: shape.stroke, place: pos, opaque: opaque, clip: clip, visible: visible, tag: tag)
        }
        if let text = referenceNode as? Text {
            return Text(text: text.text, font: text.font, fill: text.fill, stroke: text.stroke, align: text.align, baseline: text.baseline, place: pos, opaque: opaque, clip: clip, visible: visible, tag: tag)
        }
        if let image = referenceNode as? Image {
            return Image(src: image.src, xAlign: image.xAlign, yAlign: image.yAlign, aspectRatio: image.aspectRatio, w: image.w, h: image.h, place: pos, opaque: opaque, clip: clip, visible: visible, tag: tag)
        }
        if let group = referenceNode as? Group {
            var contents = [Node]()
            group.contents.forEach { node in
                if let copy = copyNode(node) {
                    contents.append(copy)
                }
            }
            return Group(contents: contents, place: pos, opaque: opaque, clip: clip, visible: visible, tag: tag)
        }
        return .none
    }
```

About content scale - very strange, it can be a bug, did you set content mode after updating node?

**Comment by amarunko** [comment]
I will try to test case with one shared node for 2 or more MacawViews. I hope we can fix this loops.

**Comment by lubiluk** [comment]
Thanks, I was searching for a way to copy a node. 

Content mode works well if I set it in code, it just ignores the value set in interface builder. SVGView however respects setting from interface builder.

**Comment by lubiluk** [comment]
I tried release version 0.9.3 as well as latest master. Both installed with carthage.

**Comment by f3dm76** [comment]
Hello lubiluk,
We introduced some major changes to inner Macaw organization which allowed the usage of one node in multiple places. You are welcome to try it out. Please let us know if there are still problems.

**Comment by ystrot** [comment]
Should be working in the 0.9.4 release.

**Comment by K-Be** [comment]
I've faced with same issue in the 0.9.4 release.

**Comment by Sega-Zero** [comment]
Still facing this
