### ISSUE TITLE
CALayer bounds contains NaN - Exception

### ISSUE THREAD

**Issue by ElyDantas** [exyte/Macaw#489]
#### `*** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer bounds contains NaN: [0 0; nan nan]' ***`

This error just appeared when i updated my project and it's pods to **swift 4.2**.

Then i cloned Macaw-Examples(HealthStat) trying to replicate the error and it did.

`DailySummaryView` specifically throw that exception while creating an `Arc` object. 

App will run if this line of code is commented on `play()` method:
`animations.forEach { $0.play() }`

Probably the error is in some part of `Shape` init method !?

<img width="968" alt="exception" src="https://user-images.githubusercontent.com/12100371/46831403-bd920380-cd79-11e8-8e35-23b2ba5b3e79.png">

After `ctx.boundingBoxOfPath` width and height becomes `-inf`

**Comment by amarunko** [comment]
Hi, @ElyDantas, can you try the version from the master branch? We solve the issue with crashing during an animation, if you can reproduce another crash - please let us know.

**Comment by ElyDantas** [comment]
It's working fine now. I'll stay tuned for more bugs 🐞 thanks @amarunko

**Comment by ystrot** [comment]
Closing this issue, once the fix available in master and will be part of 0.9.2 release.
