### ISSUE TITLE
Support group selectors in CSS part of SVG

### ISSUE THREAD

**Issue by lukaszkrystek** [exyte/Macaw#493]
Some SVG files don't display properly. 
They display properly in browsers (Chrome, Safari). However, using Macaw (iOS/macOS) they do not display correctly.
Please see attached files.

[SVG_not_supported.zip](https://github.com/exyte/Macaw/files/2514646/SVG_not_supported.zip)

**Comment by ystrot** [comment]
Hi lukaszkrystek,

As for Europe sample, Macaw currently doesn't support xmlns. So if you remove all "svg:" strings from your file, the map will be shown correctly.

Another issue looks like a bug, we'll take a look what's wrong here.

**Comment by explaineverything** [comment]
Hi, thanks for response.

It's great, that you will take a look on the another issue.

Is there any chance, that xmlns will be supported in the future? Or maybe the Macaw would skip this parameter and display the file?

**Comment by lukaszkrystek** [comment]
Hi, thanks for response.

It's great, that you will take a look on the another issue.

Is there any chance, that xmlns will be supported in the future? Or maybe the Macaw would skip this parameter and display the file?

**Comment by ystrot** [comment]
I've fixed issue with the second SVG and open another ticket for xmlns support: https://github.com/exyte/Macaw/issues/494.

**Comment by explaineverything** [comment]
Great thanks, now it works very good! 
So only support for XML namespaces is the last thing I think.

**Comment by lukaszkrystek** [comment]
Great thanks, now it works very good!
So only support for XML namespaces is the last thing I think.

**Comment by ystrot** [comment]
@lukaszkrystek JFYI #494 fixed as well, so all your samples should work now.

**Comment by lukaszkrystek** [comment]
Yes thanks, attached earlier SVG files works very good!

But there are still some files, which doesn't open properly. Can you see attached files?

`04. Seal_of_Ohio.svg` -	missing some letters and graphic elements
					SVG parsing error. Shape perspective not supported
				      	SVG parsing error. Shape perspective not supported
					SVG parsing error. Shape metadata not supported
					SVG parsing error. Shape namedview not supported

`Education icon.svg` - SVG parsing error. Shape desc not supported

`Achaemenid_(greatest_extent).svg` - additional, not needed line

`Explain Everything Wordmark.svg` - SVG parsing error. Shape desc not supported - missing few letters in “Explain Everything”

`SVG_logo.svg` - missing some graphic coloured elements

`Diamond-caution.svg` - missing colours, only black

`Greece_in_the_European_Union_on_the_globe_(Europe_centered).svg` - missing  some colours, e.g. red colour for Greece

`Europe_polar_stereographic_Caucasus_Urals_boundary3.svg` - missing graphic elements/shapes
												   	   SVG parsing error. Shape namedview not supported
													   SVG parsing error. Shape metadata not supported

[SVG files.zip](https://github.com/mchoe/SwiftSVG/files/2518580/SVG.files.zip)
