### ISSUE TITLE
CocoaPods could not find compatible versions for pod "Macaw"

### ISSUE THREAD

**Issue by SDGMazeGeek** [exyte/Macaw#504]
<img width="682" alt="screen shot 2018-10-31 at 4 44 24 pm" src="https://user-images.githubusercontent.com/38777667/47783243-648c0e80-dd2c-11e8-9882-3ce20bc77439.png">

![screen shot 2018-10-31 at 4 45 10 pm](https://user-images.githubusercontent.com/38777667/47783278-7b326580-dd2c-11e8-98d2-8f2ede2a4f91.png)

**Comment by ystrot** [comment]
Pod reference looks fine, most probably you need to run "pod repo update".

**Comment by ystrot** [comment]
Closing this issue. Please open new ticket if you have another issue.

**Comment by MuhammadNayabButt** [comment]
@SDGMazeGeek  I resolved the same issue using "pod repo update"
