### ISSUE TITLE
Get compile error in Xcode10.1 swift 4.2

### ISSUE THREAD

**Issue by icefox57** [exyte/Macaw#505]
![image](https://user-images.githubusercontent.com/1716737/47843866-db440d00-ddfb-11e8-83a1-8cc692d26870.png)

**Comment by f3dm76** [comment]
Hello, are you using 'master' branch?

**Comment by icefox57** [comment]
yes ,     pod 'Macaw', '~> 0.9.3'

**Comment by amarunko** [comment]
@icefox57 that mean you use swift 4.0/4.1 version, can you share your pod file?

**Comment by icefox57** [comment]
platform :ios, ’10.3’
use_frameworks!

target ‘StitchCameraSDK’ do
    pod 'Macaw', '0.9.1'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end
end

**Comment by amarunko** [comment]
@icefox57, but here in pod file - you wrote that Macaw should be compiled with swift 4.0 version. The last release of Macaw worked only with swift 4.2. You can use previous releases, or branch swift-4.1.x or change swift version in your pod file for Macaw to 4.2.

**Comment by icefox57** [comment]
thank you very much
