### ISSUE TITLE
SVG coordinates do not respect screen size

### ISSUE THREAD

**Issue by DmitryPR** [exyte/Macaw#508]
SVG parser does not respect the screen resolution when parsing the coordinates
https://github.com/exyte/Macaw/blob/bbb9a60866c84c5bf0750276da62d9d3d43846bf/Source/svg/SVGParser.swift#L748

For example our test iPhone 6 plus with 1080x1920 resolution, I can only draw SVGs with coordinates with up to 450x736. 

If I supply `<svg width="1080" height="1920"><circle cx="420" cy="20" r="5"></svg>`

then  it won’t be drawn

**Comment by ystrot** [comment]
Hi Dmitry,

Probably you need to use content layout: https://github.com/exyte/Macaw/wiki/Understanding-MacawView-content-layout

**Comment by ystrot** [comment]
Great! Closing this issue.
