### ISSUE TITLE
Need a Demo Morphing project using svg file

### ISSUE THREAD

**Issue by mediym41** [exyte/Macaw#509]
Can you share svg file 'examples' from https://github.com/exyte/Macaw/wiki/Morphing-animation ?
I have to do transition from one svg object to another.

**Comment by ystrot** [comment]
Unfortunately we lost this SVG 😔 However you can take any two SVG files made in one style and add morphing using following code:
```Swift
let sample1 = try! SVGParser.parse(path: "sample1")
let sample2 = try! SVGParser.parse(path: "sample2")

let rootGroup = [sample1].group()
rootGroup.contentsVar.animation(to: [sample2], during: 3.0).autoreversed().cycle().play()
```

**Comment by ystrot** [comment]
Closing this issue. Please reopen it or create another one if you have more questions.
