### ISSUE TITLE
CALayerInvalidGeometry - Exception

### ISSUE THREAD

**Issue by ElyDantas** [exyte/Macaw#510]
` *** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer bounds contains NaN: [0 0; nan nan]'`

Macaw-Examples:
Error found while launching HealthStat.
Error found while pressing "ADD A TASK" option in DesignAwardedApps/Streaks.
Error found while pressing play button in DesignAwardedApps/Auxy.

**Comment by ystrot** [comment]
Hi Ely,

Thanks for reporting! This issue fixed in the `master` version, so please use it for now. We'll release it in the nearest time.

**Comment by ystrot** [comment]
Closing this issue since 0.9.4 is out.
