### ISSUE TITLE
Arc animation overlap

### ISSUE THREAD

**Issue by ElyDantas** [exyte/Macaw#511]
I use HealthStat's circular graph in my project and one of user's interactions is a set of buttons corresponding to week days, each day pressed run the same animation with different data.

Overlap of arcs occurs when buttons are pressed in middle of animation.
`stop()` animations and `animations.removeAll()` before triggering new animations doesn't clean arcs interrupted in middle of their animations.

Got a way around making sure it animates only when last animation is complete, but user experience is decreased by this delay.

```
animations.forEach {
            $0.play()
            $0.onComplete {
                self.isPlaying = false
            }
}
```

Couldn't launch HealthStat's project from Macaw-Examples #510 to make it replicable. But bug could be replicated using HealthStat's animation being triggered by a button, pressing it in the middle of animation.

**Comment by ystrot** [comment]
Hi Ely,

Since #510 works on master, could you please show a sample? I've checked that `Animation.stop` works fine, so if you just stop animation and start another one with the new data everything should works as expected.

**Comment by ElyDantas** [comment]
Thanks @ystrot for the heads up, here's the behaviour i'm experiencing:

![screen shot 2018-12-11 at 17 15 02 copy](https://user-images.githubusercontent.com/12100371/49827914-44a72c00-fd69-11e8-8bdc-7846b0e8b5b4.png)

I created a screen tap gesture to start Daily Summary animation.
If you tap screen in different times during animation, arcs will start to leave traces of themselves in the graph.

```
open override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)

        let tap: UITapGestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(animateViews))
        tap.cancelsTouchesInView = false
        view.addGestureRecognizer(tap)

    }

    @objc open func animateViews() {
        dailySummaryView.stop()
        dailySummaryView.play()
    }
```
Here's what i'm getting in my project:

- Before

![img_8022 copy](https://user-images.githubusercontent.com/12100371/49828293-46252400-fd6a-11e8-8746-f9f9667bfa9f.jpg)

- After

![img_8024 copy](https://user-images.githubusercontent.com/12100371/49828296-47eee780-fd6a-11e8-85e2-c9cb07cc64b8.jpg)

**Comment by ystrot** [comment]
Thanks for detailed report. You have this issue, because in the HealthStat scene recreated on every play. You can modify `DailySummaryView` to avoid it:
```Swift

    private var initialized = false

    open func play() {
        animations.forEach { $0.stop() }
        // create scene just once
        if (!initialized) {
            initialized = true
            createScene()
        }
        createAnimations()
        animations.forEach { $0.play() }
    }
```
In this case you don't need a separate `stop` method, because existing animations will be stopped when you call `play`. It just a working sample, so in your case it would be better to create scene once in an initializer to avoid `initialized` property and then only restart animations when necessary.

**Comment by ElyDantas** [comment]
Thanks @ystrot, indeed that was the wrong implementation path i was running into. I do have no more arc's trace in multiple animation sequences, but i ran into another issue, graph's `[Text]` array that show clock numbers around it makes arc's animation lazy after several animations, like 50-100 anim repeats, animating without text with the same created scene removes laziness, when animating with text again in same scene it brings back laziness in animation. Do you have any thoughts ?

**Comment by ystrot** [comment]
Is this text animated as well? Would be great if you can show some code example. Usually animation slowness appears because some animations wasn't removed properly. However it might be Macaw issue, so need to take a look to a sample.

**Comment by ystrot** [comment]
Closing this ticket. Feel free to create another one if you have more questions.
