### ISSUE TITLE
SVG pinch/zoom performance?

### ISSUE THREAD

**Issue by philmitchell** [exyte/Macaw#513]
I load an svg file into `MacawView` and manually update `node.place`, along with `view.bounds`. It works very nicely, except performance is a little sluggish. Is there a better way?

Also, it's not hard to get a memory crash if you zoom way in .... 

```swift
    @objc func didPinch(pinchGestureRecognizer: UIPinchGestureRecognizer) {
        let node = macawView.node
        let scale = pinchGestureRecognizer.scale
        let location = pinchGestureRecognizer.location(in: macawView)
        let dx = Double(location.x * (1 - scale))
        let dy = Double(location.y * (1 - scale))
        node.place = node.place
          .scale(sx: Double(scale), sy: Double(scale))
          .move(dx: dx, dy: dy)
        let transform = CGAffineTransform.identity.scaledBy(x: scale, y: scale)
        macawView.bounds = macawView.bounds.applying(transform)
        pinchGestureRecognizer.scale = 1.0
    }
```

**Comment by ystrot** [comment]
Hi Phil,

Did you use some SVG to reproduce it? Would be great if you can attach it. I believe it depends on SVG complexity in your case.

**Comment by ystrot** [comment]
There is now `MacawView.zoom` property with a pretty fast zoom/pinch feature.
