### ISSUE TITLE
Can we support more units in SVG ?

### ISSUE THREAD

**Issue by wjling** [exyte/Macaw#516]
I parse a svg file, but I get error: `SVG parsing error. Unit ex not supported`. Can we support more units?

**Comment by amarunko** [comment]
Hi, @wjling, unfortunately, we don't support ex for now, but extending SVG parser - it is a high priority task for Macaw team, we will try to cover all possible units. You always can help us by sending PR, thanks.

**Comment by wjling** [comment]
Ok, I see. Thank you for your excellent work
