### ISSUE TITLE
ContentMode not working

### ISSUE THREAD

**Issue by EternalBlack** [exyte/Macaw#517]
I currently use `Macaw 0.9.3`. and cant seem to get the contentMode working (`MacawView` and `SVGView`)

Neither via storyboard, nor via code. It kinda seems like I'm missing something.

```
import UIKit
import Macaw

class SVGViewController: UIViewController {

    @IBOutlet weak var macaw: MacawView!
    @IBOutlet weak var svgView: SVGView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let tiger = try! SVGParser.parse(resource: "tiger")
        self.macaw.node = tiger
        self.macaw.backgroundColor = .darkGray
        self.macaw.contentMode = .scaleToFill

        self.svgView.node = tiger
        self.svgView.backgroundColor = .darkGray
        self.svgView.contentMode = .scaleToFill
    }
}
```

The tiger.svg is shown on both but seems to be using `.scaleAspectFit` (by default I guess).

> Big Scope:
What I'm actually trying to archive is masking a UIView with and SVG file. but therefor I need the SVG to `.scaleToFill` the other view (i.e. ```svgView.contentMode = .scaleToFill; svgView.frame = content.frame`; content.mask = svgView;```)

**Comment by EternalBlack** [comment]
Hey @amarunko,
I actually used the example project with no changes but adding the viewController you see above with the two UIViews connected to the IBOutlets.

**Comment by EternalBlack** [comment]
@amarunko Thanks for the hint! Removing the `viewbox` from the SVG does the trick.

I previously found (searching for `contentMode` inside the repo) #218 and somewhat expected the `tiger.svg` to work as it seemed to work back there. Are there any plans to reimplement the `contentMode` for SVGs **with** a `viewbox`? Or is #218 misleading?

Would be nice to add this important/required info to the [docs](https://github.com/exyte/Macaw/wiki/Understanding-MacawView-content-layout). :)

**Comment by ystrot** [comment]
Hi Markus,

#218 is misleading in this case, because we changed `tiger.svg` since that time and added `viewbox` there. I think we'll revert these changes to avoid confusion you mentioned. `contentMode` works as expected, so we'll update documentation to highlight that in case of `viewbox` there will be no effect of using `contentMode`. Thanks for point this out!
