### ISSUE TITLE
Animation on OSX hangs

### ISSUE THREAD

**Issue by wildthink** [exyte/Macaw#522]
The recently added `CombinationAnimationGenerator.swift` fails to compile for OSX.
Adding
```
#if os(OSX)
import AppKit
#else
import UIKit
#endif
```
fixes the build but the animation example in the OSX Example hangs.

**Comment by amarunko** [comment]
Hi, @wildthink, thanks, build fixed in the master branch. Also, you always can send fixes by pull request. We will investigate hangs.

**Comment by ystrot** [comment]
This issue fixed in the master branch and will be available in the 0.9.4 release.
