### ISSUE TITLE
Getting Path

### ISSUE THREAD

**Issue by lukaszkrystek** [exyte/Macaw#524]
Is there any way to get CGPath object (or UIBezierPath) from any .SVG file? 
I think, there should be such way, because Macaw uses CGContext to draw paths. I'd like to put CGPath to CAShapeLayer then. Thanks for response.

**Comment by explaineverything** [comment]
Hi @ystrot , thanks for the response.
The shape variable from your code is of type Group. So is it good idea to create multiple layers, each for Shape, Text or Image?

**Comment by lukaszkrystek** [comment]
Hi @ystrot , thanks for the response.
The shape variable from your code is of type Group. So is it good idea to create multiple layers, each for Shape, Text or Image?

**Comment by ystrot** [comment]
So, if you specify id of `<g>` instead of `<path>` it will definitely crash 😄 And yes, if you want to draw some text and image you also need to get it from a SVG and draw.

**Comment by lukaszkrystek** [comment]
One more question: is there an easy way to use Macaw to render SVG files in CAShapeLayer, instead of using SVGView, which is built on CGContext? Thanks

**Comment by ystrot** [comment]
You can render your file to a `UIImage` using `node.toNativeImage` method, which you can use for rendering on `CAShapeLayer`.

**Comment by lukaszkrystek** [comment]
Yes I understand ;)
But I don't want to create UIImage, because during scaling layer with UIImage (applying CGAffineTransform), the quality would be low and re-creating UIImage would be needed. If I use CAShapeLayers with CGPaths, the re-rendering during applying transform is automatic. So my question is: Can I create CAShapeLayers with CGPaths somehow using Macaw?

**Comment by lukaszkrystek** [comment]
I think, that it would be good improvement for the whole library to render SVG as CALyers tree.

I have the problem with SVGView - when I scale it by any value, e.g. I make it 3-5 times bigger, the SVG is not re-rendered and the quality is low. 

I set transform like this: `svgView.transform = CGAffineTransform.init(scaleX: 5, y: 5)`
And the result is on attached screenshot.
![screenshot 2019-02-05 at 15 44 15](https://user-images.githubusercontent.com/13151687/52280812-012e0000-295d-11e9-80fc-1b224d7e5d4b.png)

Do you know how can I re-render the `SVGView: MacawView` to apply scale to it and render only visible on screen part of SVG? Thanks.

**Comment by ystrot** [comment]
You need to apply scale to a node instead. Something like this:
```
svgView.node.place = svgView.node.place.scale(sx: 5, sy: 5)
```

**Comment by ystrot** [comment]
Closing. Feel free to create another issue if you have more questions.

**Comment by explaineverything** [comment]
Ok thanks for your help!

**Comment by lukaszkrystek** [comment]
Ok Thanks for your help!
