### ISSUE TITLE
SVGParser.parse() memory leak

### ISSUE THREAD

**Issue by red16035** [exyte/Macaw#528]
Hello, 

I parse and load multieple SVG files from UIViewPageController.
changed viewpage, but did  not remove from memory. 

x code memory graph screen shot: 
https://drive.google.com/file/d/1XA5sPeOtipf80hiA_COyqvwh4_x-x51r/view?usp=sharing

help me please...

thanks.

**Comment by amarunko** [comment]
Hi, @red16035, thank you for the detailed graph, we will investigate the issue.

**Comment by manindaniil** [comment]
Hi, @red16035 !
This issue fixed in the master branch, thank you for reporting!
