### ISSUE TITLE
Scrollable Scene.

### ISSUE THREAD

**Issue by Fames42** [exyte/Macaw#531]
Hi there! I am new in ios development and i have a question: is there any method or implementation of making macaw scene scrollable. Example: periodic table example is not fits in my iphone 6, so i want big scene to be scrollable +zoom functionality.  Is something exist that can do it in Macaw?

**Comment by ystrot** [comment]
Hi @Fames42,

We're planning to include built-in zooming for `MacawView` in the next release.

**Comment by ystrot** [comment]
`MacawView.zoom` is available.
