### ISSUE TITLE
MGIsDeviceOneOfType is not supported on this platform.

### ISSUE THREAD

**Issue by Trazmor** [exyte/Macaw#532]
I tried to run the example HealthState with XCode 10 on an iPad Pro and it crashes at the very start

<img width="1280" alt="screenshot 2019-02-26 at 19 32 53" src="https://user-images.githubusercontent.com/16354899/53437265-61184380-39fd-11e9-825d-a2c8c3da2067.png">

**Comment by amarunko** [comment]
Hi, @Trazmor, I think the issue - is nan geometry param, not MGIsDeviceOneOfType, we will investigate this issue, thank you for reporting

**Comment by ystrot** [comment]
Currently `HealthStat` works correctly on the latest Xcode 10.2. Please reopen this issue if you still have some issues with it.
