### ISSUE TITLE
Render a node into CGContext

### ISSUE THREAD

**Issue by K-Be** [exyte/Macaw#533]
Good day. 
I want to render a Node into an UIImage context, but can't find solution for this :(.     
All renderers have internal visibility. How I can render a Node into CGContext?    
(I use 0.9.4 version)

**Comment by ystrot** [comment]
Hi Andrew,

There is `Node.toNativeImage` method which you can use.

**Comment by K-Be** [comment]
I missed that method, thank you. Can this method works in a  background thread??

**Comment by ystrot** [comment]
Yes, it should works in background as well.
