### ISSUE TITLE
Animated SVG is not animating into SVGView

### ISSUE THREAD

**Issue by Dhvl-Golakiya** [exyte/Macaw#540]
I have one animated SVG and want to load it in `SVGView`. I have set `SVGView` in Xib and set filename there.
 The SVG file is loading into view but it is not animating. I can load this SVG into `UIWebView` and it is animating also. Also, I tried to parse it by this way:
```
        let path = Bundle.main.path(forResource: "sun", ofType: "svg")
        let examples = try! SVGParser.parse(fullPath: path!)
```
but getting this error `SVG parsing error. Shape clipPath not supported`. Please tell me what I am doing wrong so I can fix it.

SVG file: 
[sun.svg.zip](https://github.com/exyte/Macaw/files/2935009/sun.svg.zip)

**Comment by ystrot** [comment]
Hi Dhaval,

Unfortunately Macaw doesn't support SVG animation. However your SVG is quite simple, you can do the same using plain Macaw model. Check out this tutorial for more information: https://github.com/exyte/Macaw/wiki/Getting-started

**Comment by glennposadas** [comment]
@ystrot can we animate changing of fill of Shapes of an SVG? Cause I tried it. Nothing happens. Only if we do the normal method, shape.fill = someFill.

**Comment by ystrot** [comment]
Yes, you should be able to call `shape.fillVar.animate(...)` on a node of your SVG. If it doesn't work for you, please attach a sample we can use to reproduce this issue.

**Comment by ystrot** [comment]
Closing this one. Please open another ticket if you have another question/issue.
