### ISSUE TITLE
How to scale rendered svg

### ISSUE THREAD

**Issue by nsandeepa** [exyte/Macaw#542]
Hi,
I need to know how to scale a svg by applying `node.place = node.place.scale(sx: 2.0, sy: 2.0)`
I tried answers on issues regarding scaling but none of them seem to be working. I have created a view extending `MacawView`. I need to scale the svg on onTap. Here is my code.
```
open class ACVSVGView: MacawView {
    
    private var currentFillColor: Color = Color.aqua
    
    init(node: Node) {
        super.init(frame: CGRect.zero)
        self.node = node
    }
    
    public convenience required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    public override func handleTap(recognizer: MTapGestureRecognizer) {
        self.node.place = self.node.place.scale(sx: 2.0, sy: 2.0)
    }
    public func setCurrentFill(color: Color) {
        self.currentFillColor = color
    }
}

```

**Comment by ystrot** [comment]
Hi Nilupul,

The scaling code is fine. But you shouldn't override `handleTap` method. You need to add your own tap gesture recognizer and add scaling there.

**Comment by nsandeepa** [comment]
Hello @ystrot 
I tried with tap gesture adding a separate UIView and scaling svg from there but it did not work. But I used Macaw Content Layout to do what i needed. Thank you for your answer btw.
