### ISSUE TITLE
[Help] Add Text Inside a Rect?

### ISSUE THREAD

**Issue by glennposadas** [exyte/Macaw#544]
Hi, great library by the way. Much much extensive compared to the other two that I've tried. So what I'm trying to do is to draw a `Text` inside a `Shape`.

To add more context, these are the squares that I will need a text to put into:

<img width="443" alt="Screen Shot 2019-03-13 at 3 31 24 PM" src="https://user-images.githubusercontent.com/12502679/54261179-09a1d800-45a6-11e9-81e7-9eacbe44fcc3.png">

However, when I attempt to add Text objects, they're being added outside any shapes in the SVG. See the screenshot.

And here's my attempt:

```
extension Group {
    var allShapes: [Shape] {
        get {
            var shapes = [Shape]()
            for shape in self.contents {
                if let shape = shape as? Shape {
                    
                    shapes.append(shape)
                    
                    if shape.tag.contains("#f0f") || shape.tag.contains("#ff00ff") {
                        // Magenta
                        // Rect
                        print("PLACE: \(shape.place.dx) \(shape.place.dy)")
                        let text = Text(text: "A", clip: shape.bounds?.center())
                        
                        let text2 = Text(text: "C", place: .move(dx: shape.place.dx, dy: shape.place.dy))
                        
                        text.fill = Color(val: 0x33FCFF)
                        text2.fill = Color(val: 0x33FCFF)
                        
                        self.contents.append(text)
                        self.contents.append(text2)
                    }
                    
                    
                } else if let group = shape as? Group {
                    _ = group.allShapes.map { shapes.append($0) }
                }
            }
            
            return shapes
        }
    }
}
```

Thank you!

**Comment by ystrot** [comment]
Hi Glenn,

You need to use both shape bounds and its place to find the center. Also you need to align text relative to the center. Here is the code that should work:
```Swift
let center = shape.bounds!.center()
let cx = shape.place.dx + center.x
let cy = shape.place.dy + center.y
let text2 = Text(text: "C", align: .mid, baseline: .mid, place: .move(dx: cx, dy: cy))
```

**Comment by glennposadas** [comment]
Awesome!!! One last question before I close this, how to make Text occupy the shape?

**Comment by ystrot** [comment]
What do you mean? If you want to set a background to replace original shape, then you need to create another shape with the color you need.

**Comment by glennposadas** [comment]
Sorry if it wasn't clear. I'd like to size up the `Text` based on the size of the squared magenta `Shape`.

**Comment by tarunsachdeva001** [comment]
Hello, I think Gleen need that text fill the shape. As we see the text is outside the magenta box.

**Comment by ystrot** [comment]
If you need to scale text to fit the shape, you may add the following code after text creation:
```Swift
let shapeSize = shape.bounds!.size()
let textSize = text2.bounds.size()
let sx = shapeSize.w / textSize.w
let sy = shapeSize.h / textSize.h
let scale = min(sx, sy)
text2.place = text2.place.scale(sx: scale, sy: scale)
```

**Comment by glennposadas** [comment]
GREAT!!! You did it. Thank you very much!
