### ISSUE TITLE
How Can I remove the text from particular shape ?

### ISSUE THREAD

**Issue by tarunsachdeva001** [exyte/Macaw#549]
Hello, I append text with particular node/shape but now I want to remove the text on click on that shape. I already got the shape object and change that shape color, but I can't remove the text from that shape. Please help me on this.

**Comment by ystrot** [comment]
Hi Tarun,

You need to change `contents` of a `Group` where you added your text. Let's say you have:
```swift
let shape = Shape(...)
let text = Text(...)
let group = Group(contents: [shape, text])
...
```

then on click you need to do the following:
```swift
group.contents = [shape]
```

**Comment by tarunsachdeva001** [comment]
Thank you so much . Really helpful. Before closing the issue, One more thing my svg image become blur when I zoom that image. Can you please suggest why it becomes blur. Thanks in advance.

**Comment by tarunsachdeva001** [comment]
And if I increase the size of my SVG then now the svg is not blurry but it shows only a part of svg on screen.

**Comment by ystrot** [comment]
Hi Tarun,

Regarding zooming please check out this comment: https://github.com/exyte/Macaw/issues/550#issuecomment-475560297

**Comment by tarunsachdeva001** [comment]
Okay Thank you so much for help. 👍
