### ISSUE TITLE
swift version issue

### ISSUE THREAD

**Issue by wangwentong-lunaon** [exyte/Macaw#557]
SWIFT_VERSION = 3.0 bug xcode of 10.2 is not Compatible, how to fix it ?

**Comment by wangwentong-lunaon** [comment]
Showing Recent Messages
:-1: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'SWXMLHash')

**Comment by amarunko** [comment]
Hi, @wangwentong-lunaon , It is because swift 3 support dropped in Xcode 10.2, can you try to update SWXMLHash pod? (pod update SWXMLHash)

**Comment by wangwentong-lunaon** [comment]
I use the latest version of SWXMLHash,  have same issue

**Comment by amarunko** [comment]
Okay, I will look into, but for me - all works as expected on master branch, did you use master branch?

**Comment by wangwentong-lunaon** [comment]
<img width="1126" alt="屏幕快照 2019-03-29 下午1 44 05" src="https://user-images.githubusercontent.com/39506652/55211901-e07d7a80-5228-11e9-9a87-a2e5db7eaeba.png">
<img width="1043" alt="屏幕快照 2019-03-29 下午1 44 21" src="https://user-images.githubusercontent.com/39506652/55211925-effcc380-5228-11e9-9915-c2fe6f1a7b80.png">

**Comment by ystrot** [comment]
Try to add `use_frameworks!` to your podfile:
```
platform :ios, '10.0'
use_frameworks!
```
It works for me in this case.

**Comment by wangwentong-lunaon** [comment]
platform :ios, '10.0'
use_frameworks!

target 'test' do
  pod 'Macaw', :git => 'https://github.com/exyte/Macaw.git', :branch => 'master'
end

has same error

**Comment by amarunko** [comment]
@wangwentong-lunaon can you also attach podfile.lock?

**Comment by wangwentong-lunaon** [comment]
PODS:
  - Macaw (0.9.4):
    - SWXMLHash
  - SWXMLHash (4.8.0)

DEPENDENCIES:
  - Macaw (from `https://github.com/exyte/Macaw.git`, branch `master`)

SPEC REPOS:
  https://github.com/cocoapods/specs.git:
    - SWXMLHash

EXTERNAL SOURCES:
  Macaw:
    :branch: master
    :git: https://github.com/exyte/Macaw.git

CHECKOUT OPTIONS:
  Macaw:
    :commit: 669161a3a09b7a3a22324e25b49bee3de9741139
    :git: https://github.com/exyte/Macaw.git

SPEC CHECKSUMS:
  Macaw: f7f49014ad56e47feb48ec3cfaae45a5d1332c9e
  SWXMLHash: 6d0ab74fef35f99156945c8bfe86dd7ead0822aa

PODFILE CHECKSUM: 2ac19950d8582255154416cb7d13d048ca177b86

COCOAPODS: 1.7.0.beta.1

this is my podfile.lock

**Comment by wangwentong-lunaon** [comment]
reason is my COCOAPODS version is 1.7.0.beta.1

**Comment by zhouyijian2** [comment]
cocoapods change to 1.6.1 can resolve this problem.Maybe beta version cocoapods in project settings has some error.
