### ISSUE TITLE
Move To Specific position on svg

### ISSUE THREAD

**Issue by tarunsachdeva001** [exyte/Macaw#558]
Hello, Now my svg is working fine on svgscrollview. I am getting one issue when I try to move to specific position with cgpoint in scrollview. Actually I got points like this - shape.bounds?.center().toCG() and then move my scrollview to particular points. Please help me how can I move to particular points. Thank you.

**Comment by ystrot** [comment]
Hi Tarun,

Could you please attach a sample project and provide steps to reproduce your issue? Otherwise it's hard to understand the issue you're talking about.

**Comment by tarunsachdeva001** [comment]
Hi, Thanks for the quick response.

if shape.tag.contains("AAA") {
       guard let cgPoint = shape.bounds?.center().toCG()
scrollView.setContentOffset(cgPoint, animated: true)
}

I am using this code to move to specific location. Is it helpful ?

**Comment by tarunsachdeva001** [comment]
The main thing here is that I have to move to specific position in scrollview, and that position I got from particular shape's bounds.

**Comment by ystrot** [comment]
You're getting shape center in local coordinates and set it to the scroll view offset which should be in absolute coordinates. So you need to convert your local position to absolute position. So you need to do the following steps:
* concatenate all `place`s from root to your shape using `parent.place.concat(with: child.place)` function
* Translate your point to absolute coordinate using inverted matrix:
```swift
let absCenter = localCenter.applying(transform.toCG().inverted())
```

**Comment by tarunsachdeva001** [comment]
Okay , Let me try this .

**Comment by ystrot** [comment]
Hi Glen,

Here is how you need to update your focus function:
```Swift
@IBAction func focus(_ sender: Any) {
    let root = svgScrollView.svgView.node
    if let point = getPointToScroll(node: root, parentPlace: .identity) {
        let scale: CGFloat = 3.5
        self.svgScrollView.setZoomScale(scale, animated: false)
        self.svgScrollView.setContentOffset(CGPoint(x: point.x * scale, y: point.y * scale), animated: true)
    }
}

private func getPointToScroll(node: Node, parentPlace: Transform) -> CGPoint? {
    let absPlace = parentPlace.concat(with: node.place)
    if let group = node as? Group {
        for content in group.contents {
            if let location = getPointToScroll(node: content, parentPlace: absPlace) {
                return location
            }
        }
    } else if let shape = node as? Shape {
        if shape.fill == Color(val: Int("ffff1c", radix: 16)!) || shape.tag.contains("ffff1c") {
            print("FOUND THE SHAPE!")
            if let center = shape.bounds?.center().toCG() {
                return center.applying(absPlace.toCG())
            }
        }
    }
    return nil
}
```

Note that content offset doesn't consider zoom scale, so I've fixed it. Also you may find useful to scroll to a point so that it appear in the center instead of top left corner. It can be easily fixed by subtracting half of the view size from the offset:
```Swift
let size = view.bounds.size
...
svgScrollView.setContentOffset(CGPoint(x: point.x * scale - size.width / 2, y: point.y * scale - size.height / 2), animated: true)
```

**Comment by glennposadas** [comment]
Thank you sooooo much @ystrot. We've been figuring out this kind of feature for a couple of days now! Works great! @tarunsachdeva001 may close this now. 🎉✅👍🏿

**Comment by tarunsachdeva001** [comment]
Thank you so much for your help.

**Comment by ggirotto** [comment]
Hi guys. What you mean in this issue with `SVGScrollView` ? Was this a class that doesn't exists anymore?
