### ISSUE TITLE
Move + Scale Transform

### ISSUE THREAD

**Issue by kmalkic** [exyte/Macaw#562]
Hi, 
I think i found an issue around chaining transforms.
I loaded my svg, but wanted to place it somewhere relative to my view.
It all worked well until i applied a scale to it.

So basically this code won't do what i want: (placing the Shape in the middle of the screen)
```
let scale: Double = 2
if let node = sShape, let bounds = node.bounds {
            node.place = node.place
                .scale(sx: scale, sy: scale)
                .move(dx: Double(frame.width.half) - ((bounds.w * scale) / 2), dy: Double(frame.height.half) - ((bounds.h * scale) / 2))
                
}
```
But if i place scale afterward it will work.
```
let scale: Double = 2
if let node = sShape, let bounds = node.bounds {
            node.place = node.place
                .move(dx: Double(frame.width.half) - ((bounds.w * scale) / 2), dy: Double(frame.height.half) - ((bounds.h * scale) / 2))
                .scale(sx: scale, sy: scale)
}
```

Then I looked into the implementation and found out that a move will use the scales values, but scaling will not readjust the position dx and dy. (actually that made more sense)
```
    public func move(dx: Double, dy: Double) -> Transform {
        return Transform(m11: m11, m12: m12, m21: m21, m22: m22,
                         dx: dx * m11 + dy * m21 + self.dx, dy: dx * m12 + dy * m22 + self.dy)
    }

    public func scale(sx: Double, sy: Double) -> Transform {
        return Transform(m11: m11 * sx, m12: m12 * sx, m21: m21 * sy, m22: m22 * sy, dx: dx, dy: dy)
    }
```

Why would move use the scale? because i'm already considering it when i moved my Shape. However I do understand why you did it, but complicated to work with if you're chaining transforms. 
The same question would apply to `concat(with: Transform)`  as it also alter the move position.

Thanks

**Comment by ystrot** [comment]
Hi Kevin,

Affine transformation you're talking about is a function between affine spaces represented with a matrix. It has standard implementation it all graphics frameworks, including [Core Graphics](https://developer.apple.com/documentation/coregraphics/cgaffinetransform). You may find a lot of resources describing why it works exactly this way, for example: https://en.wikipedia.org/wiki/Affine_transformation

When you apply several transformations one by one, then you need to imagine they applied in a reverse order. For example, when you see `.move().scale().rotate()` just think about you initially rotate your object, then scale and finally move it. It will allow you better understand how it works.

**Comment by kmalkic** [comment]
Thanks for sharing! Didn't know about those concepts. 👍
