### ISSUE TITLE
[Question] UIImage to UIColor to Color

### ISSUE THREAD

**Issue by glennposadas** [exyte/Macaw#564]
Is this possible? What I did results to black color.

```
let image = UIImage(named: "pattern")!
let color = UIColor(patternImage: image)
shape.fill = Color.rgb(r: Int(color.redValue), g: Int(color.greenValue), b: Int(color.blueValue))
```

```
extension UIColor {
    var redValue: CGFloat{ return CIColor(color: self).red }
    var greenValue: CGFloat{ return CIColor(color: self).green }
    var blueValue: CGFloat{ return CIColor(color: self).blue }
    var alphaValue: CGFloat{ return CIColor(color: self).alpha }
}
```

I'm guessing it's not really possible, is it? Even the `color.redValue` yields 0.0.
What I'm trying is to fill up the shape with a patterned png image.

**Comment by ystrot** [comment]
Hi Glenn,

That's really weird part of UIKit API when you can use single class for both color and pattern image. In Macaw you can use `Pattern` class for this:
```Swift
shape.fill = Pattern(content: Image(src: "pattern"), ...)
```

**Comment by glennposadas** [comment]
Hi Yuri, I appreciate your fast reply. However, I couldn't find a class named ```Pattern``` in Macaw. 🧐

**Comment by ystrot** [comment]
Here it is: https://github.com/exyte/Macaw/blob/master/Source/model/draw/Pattern.swift

Make sure you're using the latest release, it was added not so long ago.

**Comment by glennposadas** [comment]
Yuri, it crashes however I try.

```
            func fillWithPattern(contents: Group) {
                for content in contents.contents {
                    if let shape = content as? Shape {
                        if !shape.tag.contains("background") {
                            let image = UIImage.init(named: "pattern")!
                            let mImage = Image(image: image)
                            let pattern = Pattern(content: mImage, bounds: shape.bounds!)
                            shape.fill = pattern
                        }
                    } else if let group = content as? Group {
                        fillWhite(contents: group)
                    }
                }
            }
```

The crash happens in ```renderToImage``` in NodeRenderer.swift line 228. ```img``` is nil. Thanks!

**Comment by f3dm76** [comment]
```
        let image = UIImage(named: "bla")!
        let mImage = Image(image: image)
        let pattern = Pattern(content: mImage, bounds: Rect(x: 0, y: 0, w: 50, h: 50), userSpace: true)
        let c = Shape(form: Circle(r: 100), fill: pattern, place: .move(dx: 100, dy: 100))
```
<img width="224" alt="Screenshot 2019-04-12 at 11 22 10" src="https://user-images.githubusercontent.com/9447630/56012109-1a647b80-5d15-11e9-8bc4-f4ab7631f75a.png">

1. Can't reproduce the crash, but `renderToImage` doesn't take part in Pattern rendering, maybe there's something else going on in your scene?
2. Pattern's `bounds` is a size of one tile, if you use shape's bound for it - there only be one tile
3. You should pass `userSpace` parameter to Pattern's constructor, if you are using absolute coordinates for pattern construction
