### ISSUE TITLE
Use/def tags positions completely lost

### ISSUE THREAD

**Issue by santu1990** [exyte/Macaw#565]
Hi, 

I am trying to render my svg, I see use/def tag position completely lost . There are other issue as well but these are the major one. I am just attaching the sample. Let me know your thoughts.

[MacawScrollview.zip](https://github.com/exyte/Macaw/files/3082184/MacawScrollview.zip)

**Comment by ystrot** [comment]
Hi Santosh,

As I can see there is only `faith-theme-512x512.svg` in your project and it renders quite fine:

<img src="https://i.imgur.com/ttEcTd0.png">

**Comment by santu1990** [comment]
@ystrot Yes, that SVG is working fine. I am facing issue with another one "eViewer.svg".

**Comment by ystrot** [comment]
There is no such a file in your project. Could you please attach it?

**Comment by santu1990** [comment]
[MacawScrollview.zip](https://github.com/exyte/Macaw/files/3083475/MacawScrollview.zip)

**Comment by ystrot** [comment]
Thanks for reporting. Looks like this SVG contains a lot of elements not yet supported by Macaw.

**Comment by santu1990** [comment]
@ystrot Do you have any technical readme doc , so I can jump-in quickly and fix few thing.
