### ISSUE TITLE
Get the border of a specific shape?

### ISSUE THREAD

**Issue by glennposadas** [exyte/Macaw#566]
I'm trying to change the `fill` of the border of a specific shape. I don't know if I'm correct, but border is basically `stroke`, right? I got that from Adobe AI when playing with an SVG.

The black path / border / stroke is what I'd like to fill with a certain color.
 
<img width="279" alt="Screen Shot 2019-04-26 at 3 24 02 AM" src="https://user-images.githubusercontent.com/12502679/56762581-c2c51600-67d2-11e9-93fe-aaabe154c711.png">

I'm using the old Macaw 0.9.3 and I'm trying to do this by something like:

`shape.form.stroke().stroke?.fill = Color.green`

Thank you!

**Comment by amarunko** [comment]
Hi, @glennposadas, please, can you attach your SVG? May be border - it is separate node.

**Comment by ystrot** [comment]
Hi Glenn,

Yes, most probably it's a stroke, so you can change it's color using following code:
```Swift
if let stroke = shape.stroke {
    shape.stroke = Stroke(fill: Color.green, width: stroke.width, cap: stroke.cap, ...)
}
```

**Comment by glennposadas** [comment]
@amarunko @ystrot thank you both for the fast reply. Here's the sample svg file, I'll have it remove later.

What Yuri suggested does not work unfortunately and I believe it's the same with what I've tried above.

[samplesvg.zip](https://github.com/exyte/Macaw/files/3122251/samplesvg.zip)

**Comment by ystrot** [comment]
Make sure you update all shapes you need. Your sample works pretty fine:
```Swift
let node = try! SVGParser.parse(resource: "3340_LoverofmySoultest")
updateStroke(node: node)

func updateStroke(node: Node) {
    if let shape = node as? Shape {
        if let stroke = shape.stroke {
            shape.stroke = Stroke(fill: Color.green, width: stroke.width, cap: stroke.cap, join: stroke.join, miterLimit: stroke.miterLimit, dashes: stroke.dashes, offset: stroke.offset)
        }
    } else if let group = node as? Group {
        group.contents.forEach(updateStroke(node:))
    }
}
```

<img src="https://i.imgur.com/WEDACNG.png" width="400">

**Comment by glennposadas** [comment]
Thank you, Yuri! Closed!

**Comment by ystrot** [comment]
Sure, no problem.

**Comment by harrison-fu-go** [comment]
if want to update fill color, just like: 

let node = try! SVGParser.parse(resource: "3340_LoverofmySoultest")
updateStroke(node: node)

func updateStroke(node: Node) {
    if let shape = node as? Shape {
        shape.fill = Macaw.Color....
    } else if let group = node as? Group {
        group.contents.forEach(updateStroke(node:))
    }
}
