### ISSUE TITLE
LoadFont with "bold" weight will crash

### ISSUE THREAD

**Issue by flierz** [exyte/Macaw#571]
I have an issue with getting my custom fonts to work in Macaw.

SVG file:
text id="A" font-family="Roboto-Bold, Roboto" font-size="30" font-weight="bold" line-spacing="40" fill="#FFFFFF"

It crashes in the following code for unexpectedly found nil while unwrapping an Optional value:
class func loadFont(name: String, size: Int, weight: String?) -> MFont? {
...
fontDesc = fontDesc.withSymbolicTraits(.traitBold)**!**
...
}

Hope you can fix it.
Thanks in advance.

**Comment by ystrot** [comment]
Hey @flierz,

Couldn't reproduce your issue, but fixed possible crash. I think it might occurs because you have `Roboto` font, but don't have its bold version installed. Anyway, please use the master version to check it out.

**Comment by flierz** [comment]
My issue was resolved by updating to the current master branch version, thanks a lot!
