### ISSUE TITLE
Adding icon SVG to SVGView

### ISSUE THREAD

**Issue by gaston705** [exyte/Macaw#580]
Hi 
I have posted the file and I would like to add nodes above; so I wonder how I can add a svg on another svg or also add text over
Thanks

**Comment by ystrot** [comment]
Hi @gaston705,

You probably need something like this:
```Swift
var nodes = [Node]()
nodes.append(SVGParser.parse(resource: "svg1"))
nodes.append(SVGParser.parse(resource: "svg2"))
nodes.append(Text(text: "Some note", ...))

macawView.node = Group(contents: nodes)
```

**Comment by gaston705** [comment]
Thank you for your answer @ystrot , but I would like to know if I can locate the svg with coordinates x, y and if I can enlarge the svg.
Let me explain my need; I have a map in svg and I want to add small images (svg) for each city with the coordinates x, y
Thanks

**Comment by ystrot** [comment]
You can control position of each city using `place` property:
```Swift
let map = try! SVGParser.parse(path: "map")

let city1 = try! SVGParser.parse(path: "city1")
// move city SVG on the map
city1.place = .move(dx: 10, dy: 20)

let city2 = try! SVGParser.parse(path: "city2")
// move and scale city SVG
city2.place = Transform.move(dx: 30, dy: 30).scale(sx: 0.1, sy: 0.1)

macawView.node = Group(contents: [map, city1, city2])
```

**Comment by gaston705** [comment]
Hi @ystrot thank you for your help 👍 
I'm wondering now if I can display an svg directly from an url 
I tried to download the file in the memory of the phone but when I do a search with SVGParser.parse(path: "file_name"), I can not find it.

**Comment by ystrot** [comment]
Hi @gaston705,

You can use `SVGParser.parse(text: ...)` for this.

**Comment by gaston705** [comment]
Thank you @ystrot for your help and for the library you have developed

**Comment by gaston705** [comment]
Thank you @ystrot for your help and for the library you have developed
