### ISSUE TITLE
node.toNativeImage add scale parameter

### ISSUE THREAD

**Issue by szuwest** [exyte/Macaw#588]
I use the Macaw to convert a SVG file to an Image. I found the size of image that I got was not good. It was too small in large screen.

let svgContent = String.init(data: data, encoding: String.Encoding.utf8)		
let img = try! SVGParser.parse(text: svgContent!).toNativeImage(size: Size(w: Double(size.width), h: Double(size.height)))

and then I found that in the toNativeImage function, the code below:
MGraphicsBeginImageContextWithOptions(size.toCG(), false, 1)

the third parameter had been set to 1. It means always not scale. so the Image not big enough.

can you add toNativeImage a scale parameter?  let user to decide scale parameter
I think It is necessary

**Comment by ystrot** [comment]
Hi @szuwest ,

Not sure I've got your point. If you need a bigger image then you can increase it's size:
```Swift
.toNativeImage(size: Size(w: Double(size.width) * scale, h: Double(size.height) * scale)
```

If your SVG has fixed size, you can scale it using layout attribute:
```Swift
.toNativeImage(size: ..., layout: .of(contentMode: .scaleAspectFit))
```

Does it work for you?

**Comment by szuwest** [comment]
> Hi @szuwest ,
> 
> Not sure I've got your point. If you need a bigger image then you can increase it's size:
> 
> ```swift
> .toNativeImage(size: Size(w: Double(size.width) * scale, h: Double(size.height) * scale)
> ```
> 
> If your SVG has fixed size, you can scale it using layout attribute:
> 
> ```swift
> .toNativeImage(size: ..., layout: .of(contentMode: .scaleAspectFit))
> ```
> 
> Does it work for you?

yeah, it works.

**Comment by borgeser** [comment]
It works but it's not perfect.

When I use `toNativeImage()`, I expect to have an UIImage which nicely fits on my phone screen.

However `MGraphicsBeginImageContextWithOptions()` redirects to `UIGraphicsBeginImageContextWithOptions()` on iOS. By passing 1 as the third parameter, I use a scale of 1 so it looks pixelated on a retina screen.

Multiplying the target size by the screen scale is ok but it's a workaround.

I'd rather use `MGraphicsBeginImageContextWithOptions(size.toCG(), false, 0)` by default. When using 0, the scale used is the same that the device of the screen (see https://developer.apple.com/documentation/uikit/1623912-uigraphicsbeginimagecontextwitho).

We could also add a third parameter to the `toNativeImage(size, scale, layout)`

We could also use a `UIGraphicsImageRenderer` which is more robust but sadly iOS10+.

Do you get my point?

Thanks.
