### ISSUE TITLE
How to zoom SVG in webView?

### ISSUE THREAD

**Issue by kritikaperiwal12** [exyte/Macaw#591]
SVG is loading properly on webView. But I want zoomed SVG to be load. For this i set web view.scrollview.zoomScale=2.0 in webView didFinishLoad method. But nothing happens. Can anyone help?

**Comment by ystrot** [comment]
Looks like your question is not about Macaw. You can ask such a question on stackoverflow or use Apple's forum. Or use Macaw 😉
