### ISSUE TITLE
Wrong move behavior after changing shape size

### ISSUE THREAD

**Issue by georgepedrosa** [exyte/Macaw#598]
My application creates a geometric shape and allows the user to move it with the onPan event handler and to change its size with the onPinch event handler. I successfully implemented both events and they work separately, but not one after the other. After I change its size, the shape moves differently because its bounds seem to be unchanged after being rescaled. How do I change the size of a shape/node and then move it using pan gesture correctly? This is my code:

```swift

shape.onPan { event in

     guard let node = event.node else { print("error")
           return
     }
     node.place = node.place.move(dx: event.dx, dy: event.dy)
}
        
shape.onPinch { event in

     guard let node = event.node else { print("error")
          return
     }
            
     node.place = node.place.scale(sx: event.scale, sy: event.scale)
}
```

**Comment by ystrot** [comment]
Hi @georgepedrosa,

The order of transformations is important in this case, so you need to keep track of your moves/scales and apply them accordingly:
```Swift
        
var dx: Double = 0
var dy: Double = 0
var scale: Double = 1

ellipse.onPan { event in
    guard let node = event.node else { print("error")
        return
    }
    dx += event.dx
    dy += event.dy
    node.place = Transform.move(dx: dx, dy: dy).scale(sx: scale, sy: scale)
}

ellipse.onPinch { event in
    guard let node = event.node else { print("error")
        return
    }
    scale *= event.scale
    node.place = Transform.move(dx: dx, dy: dy).scale(sx: scale, sy: scale)
}
```

**Comment by georgepedrosa** [comment]
Thanks, that helped a lot! How would you save the variables when rotating a shape around its center? I managed to rotate correctly, but the scale transformation then gets a little distorted:
```swift
shape.onRotate { event in
        guard let node = event.node else { print("error")
              return
        }

        angle += event.angle

        let center = shape.bounds?.center()

        node.place = Transform.move(dx: dx, dy: dy).scale(sx: scale, sy: scale).rotate(angle: angle, x: center.x, y: center.y)
}
```

I've also noticed, in the case of a rectangle or ellipse, the scale transformation increases or decreases its size from its origin point. Is there a way to increase its size regularly on all sides, from its center? The circle, for instance, changes size regularly from its center. I'd like to apply that same behavior to rectangles and ellipses, is it possible?

**Comment by ystrot** [comment]
Hi @georgepedrosa,

If you want to make all transformations around a center, you need to move your shape so that its center placed at `(0, 0)` point, apply all transformation and move it back. That's how [`rotate(angle:x:y:)`](https://github.com/exyte/Macaw/blob/0.9.5/Source/model/geom2d/Transform.swift#L43) work. Here is complete implementation:

```Swift
var dx: Double = 0
var dy: Double = 0
var scale: Double = 1
var angle: Double = 0

func updatePlace(event: Event) {
    guard let node = event.node, let c = node.bounds?.center() else { print("error")
        return
    }
    node.place = Transform.move(dx: c.x + dx, dy: c.y + dy).scale(sx: scale, sy: scale).rotate(angle: angle).move(dx: -c.x, dy: -c.y)
}

ellipse.onPan { event in
    dx += event.dx
    dy += event.dy
    updatePlace(event: event)
}

ellipse.onPinch { event in
    scale *= event.scale
    updatePlace(event: event)
}

ellipse.onRotate { event in
    angle += event.angle
    updatePlace(event: event)
}
```

**Comment by rbreve** [comment]
When you pinch and the object is bug and then you pan, the movement becomes very slow, this worked for me:

` view.node.onPan { (event) in
        self.dx += event.dx*self.scale
        self.dy += event.dy*self.scale
        self.updatePlace(event: event)
    }`
