### ISSUE TITLE
How to get linearGradient color

### ISSUE THREAD

**Issue by DipakKakaniya** [exyte/Macaw#601]
![Screenshot 2019-06-11 at 10 41 37 AM](https://user-images.githubusercontent.com/37933138/59245273-a28fd000-8c35-11e9-86ab-b366aeced18d.png)

**Comment by ystrot** [comment]
Hi @DipakKakaniya,

Not sure I understood your question. There is `LinearGradient` class, it has `stops` points, similar to your SVG, and each of them has `color`. You can get linear gradient from a node, for example:
```Swift
let gradient = shape.fill as! LinearGradient
```

You may find more information about Macaw model in the following tutorial: https://github.com/exyte/Macaw/wiki/Getting-started

**Comment by DipakKakaniya** [comment]
Thank you so much for help. 👍
