### ISSUE TITLE
Question:  Does Macaw have eraser functionality built in?

### ISSUE THREAD

**Issue by jforward5** [exyte/Macaw#611]
Im in desperate need of a vector library that has an eraser tool built in, and can erase paths drawn over images.  Can Macaw do this?

What would the lines of code look like?  Just a sample of initiating the eraser tool if it has one...

**Comment by ystrot** [comment]
Hi @jforward5,

There is no build-in erase tool, however you may use `clip`/`mask` properties of a `Node` to implement it.
