### ISSUE TITLE
Redraw chart?

### ISSUE THREAD

**Issue by CBAffleck** [exyte/Macaw#612]
I've adapted a chart view similar to the example to create a different color x-axis/y-axis for a light and dark mode. The first time the chart is loaded I can draw the correct color axes based on whether the app is in light or dark mode. However, once the chart is loaded, I can't figure out how to redraw it (like in the case where a user changes from dark to light mode). If I call the animate function from a viewDidAppear, the bars will be redrawn. Is there a similar way to redraw the chart axes?

**Comment by ystrot** [comment]
Hi @Campbell,

Changes of any property will force redraw. For example, you can call `MacawView.node = ...` to redraw scene completely.
