### ISSUE TITLE
Initializing with Dynamic Data

### ISSUE THREAD

**Issue by Pundora** [exyte/Macaw#615]
When using super.init(...) to initialize a MacawView, it begins to create the node, etc. Using static data, this is fine. But is there a way to delay the instantiation when I need to wait for variables to finish assigning? (i.e. from a Firestore query)

**Comment by ystrot** [comment]
Hi Roy,

You can just initialize it with an empty node (`Group()`) and when you will be ready assign the correct value:
```Swift
view.node = ...
```

**Comment by PunkStarStudios** [comment]
view.node? 
Where is the Node collection for the class found?

I have
class MacawChartView: MacawView 

And there is no .node exposed

**Comment by ystrot** [comment]
Here is [MacawView.node](https://github.com/exyte/Macaw/blob/master/Source/views/MacawView.swift#L16). Probably you're doing something wrong if you can't access it.
