### ISSUE TITLE
Question: How to get parent group of node?

### ISSUE THREAD

**Issue by duytph** [exyte/Macaw#617]
At first, thanks you for your awesome library 🥰. I have tried to read your source code for self-answering but it take so much time.

Assumption I have a `SVG` file like below:
```
<g id="parent-group">
    <path id="path1"></p>
    <path id="path2"></p>
    <path id="path3"></p>
</g>
```
If I have a node of `path1`, how can I retrieve the group it belongs to (parent-group)?

**Comment by ystrot** [comment]
Hi Duy,

Unfortunately there is no API for that, because in Macaw node can have multiple parents. But here is implementation you can use:

```Swift
private func findParent(of node: Node, in view: MacawView) -> Node? {
    return findParent(of: node, in: view.node)
}

private func findParent(of node: Node, in container: Node) -> Node? {
    if container == node {
        return container
    }
    if let group = container as? Group {
        for child in group.contents {
            if let result = findParent(of: node, in: child) {
                return result
            }
        }
    }
    return nil
}
```
