### ISSUE TITLE
[question]What is the best solution for zooming SVGView?

### ISSUE THREAD

**Issue by githubYiheng** [exyte/Macaw#621]
I am trying to use SVGView, I need to load svg file and support zooming, I have found multiple scaling related questions in the existing problem but I am not sure which one is the most beautiful, I try to add code in the scrollViewDidEndZooming method and then zoom can still see the pixel Sawtooth, I found MacawView has built-in zoom function, I want to know how to use it to support scrolling and zooming, thanks first! #

**Comment by ystrot** [comment]
Hi Yiheng,

The right way is to use built-in Macaw zoom feature. You can enable it with the following code:
```Swift
// by default scrolling and zooming will be enabled
macawView.zoom.enable()
// but you can use rotation with the following line
macawView.zoom.enable(move: true, scale: true, rotate: true)
```

**Comment by Sushhi** [comment]
Hello @ystrot,

I don't see any `zoom` property in `MacawView` object.
Any advice?

**Comment by ystrot** [comment]
Hi Emilien,

You need to use master branch, because this feature is not yet released.

**Comment by Sushhi** [comment]
Indeed, thank you! :)

**Comment by githubYiheng** [comment]
> Hi Yiheng,
> 
> 
> 
> The right way is to use built-in Macaw zoom feature. You can enable it with the following code:
> 
> ```Swift
> 
> // by default scrolling and zooming will be enabled
> 
> macawView.zoom.enable()
> 
> // but you can use rotation with the following line
> 
> macawView.zoom.enable(move: true, scale: true, rotate: true)
> 
> ```


very thankful
