### ISSUE TITLE
How to mask an image with a shape

### ISSUE THREAD

**Issue by paulstampfer** [exyte/Macaw#636]
I would like to create a squared shape and put an image inside. The image should be masked by the squared shape (as it is 3:4 portrait image).

Here is what I have. How can I make the shape mask the image so that I can see only that part of the image which is inside the shape?

```
private func createFrame() -> Node {
        let rectTool = Shape(form: Rect(x: 25.0, y: 100.0, w: 200.0, h: 200.0),
                             fill: Color.white,
                             stroke: Stroke(fill: Color.black, width: 3.0))
        let image = Image(src: "IMG_1234.jpg", w: 200, place: .move(dx: 25, dy: 100))
        
        return [
            rectTool,
            image
        ].group()
    }
```

**Comment by ystrot** [comment]
Hi @paulstampfer,

Just use a `clip` property for your image:
```Swift
image.clip = Rect(...)
```
