### ISSUE TITLE
Incompatibility with the most recent RxSwift Version

### ISSUE THREAD

**Issue by LeonardoCardoso** [exyte/Macaw#64]
There's an incompatibility with projects using `RxSwift 3.0.0-beta.2` since `Macaw` uses `3.0.0-beta.1` as dependency.
Are you planning to wait the new `RxSwift` RC version to update `Macaw` or will you update to `3.0.0-beta.2`?

**Comment by vhailor13** [comment]
Thanks for reporting this issue! Fixed, now wer are using recently released RxSwift 3.0. You can use it via:
```
pod 'Macaw', :git => 'https://github.com/exyte/Macaw.git'
```
