### ISSUE TITLE
Adding shapes to SVGViews

### ISSUE THREAD

**Issue by Sushhi** [exyte/Macaw#642]
Hello guys,

I'm currently developing an app that display a **map in SVG**, in a SVGScrollView.

I'd like to pin `points of interests` on that map. Is it possible to pin a shape (a circle) on a SVGView ?

If not, any suggestion to achieve that ?

Thanks in advance for your help.

**Comment by ystrot** [comment]
Hi Emilien,

What do you mean by "pin a shape"? If you want to highlight it somehow you can change its stroke, something like this:
```Swift
shapeToPin.stroke = Stroke(fill: Color.red, width: 3)
```

If you want to put a pin icon (which can be just a circle) then you can do it in a separate layer. For example:
```Swift
let map = try! SVGParser.parse(resource: "map")
let pin1 = Shape(...)
let pin2 = Shape(...)
let pinLayer = Group(contents: [pin1, pin2])
let scene = Group(contents: [map, pinLayer])
```
