### ISSUE TITLE
SVG gradients

### ISSUE THREAD

**Issue by mixmastertube** [exyte/Macaw#644]
As I understand there's still no support for parsing SVG gradients, right? I get a white circle instead.
This would be the expected result.

<img width="113" alt="Screenshot 2019-11-28 at 15 06 26" src="https://user-images.githubusercontent.com/81303/69812583-b7b2e800-11f0-11ea-82ff-882e87bb286b.png">

`<svg width="109" height="109" viewBox="0 0 109 109" fill="none" xmlns="http://www.w3.org/2000/svg">
<circle cx="54.5" cy="54.5" r="54.5" fill="url(#paint0_linear)"/>
<defs>
<linearGradient id="paint0_linear" x1="54.5" y1="0" x2="54.5" y2="109" gradientUnits="userSpaceOnUse">
<stop stop-color="#F01A1A"/>
<stop offset="1" stop-color="#C4C4C4" stop-opacity="0"/>
</linearGradient>
</defs>
</svg>`

**Comment by amarunko** [comment]
@mixmastertube can you try to use the master branch? Fix for gradients not in release yet.

**Comment by ystrot** [comment]
This sample works fine in the master branch, closing this issue.

**Comment by mixmastertube** [comment]
How did you do it?
I did try and still not working, I still don't get any gradient.

My steps:

Step 1 
Cloning the project to local (master branch selected)

Step 2 
Editing the Podfile inside the Example folder to
pod 'Macaw', :git => 'https://github.com/exyte/Macaw.git', :branch => 'master'
just to be sure it's pointing to master branch.

Step 3
I change the svg inside the Assets folder tiger.svg to my svg, just to do a quick test.

I run the app and get a black circle instead of the expected gradient.
