### ISSUE TITLE
[Cocoapods] [0.9.5] Missing `MacawZoom`

### ISSUE THREAD

**Issue by duytph** [exyte/Macaw#648]
**Environment:**

- MacOS: macOS Catalina
- Cocoapods: 1.8.4
- Macaw: 0.9.5

**Description**

`MacawZoom` is missed after installing by `pod install`. I encounter this recently, it's look like someone's mistake because I am able to find it git repo. Hope you guys fix this issue soon.

Thanks for your awesome library, I really enjoy it.

**Comment by ystrot** [comment]
Hi Duy,

That's right, `MacawZoom` will be released in 0.9.6 version. However you can switch to the master branch to use this feature now.

**Comment by duytph** [comment]
Great, can I buy you a coffee ☕️

**Comment by duytph** [comment]
Just one more things before I go :))).
It would be nice to have zoom/scroll boundaries. In many situations I don't think user should zoom in too much.

**Comment by GDGapps** [comment]
hello @ystrot , I still don't see the zoom feature in 0.9.6 version. has it been postponed?
Thanks!

**Comment by ystrot** [comment]
Yes, we're still working on several features in the master branch, but released 0.9.6 with Swift 5.2 support only.
