### ISSUE TITLE
Can't custom view using code?

### ISSUE THREAD

**Issue by tospery** [exyte/Macaw#656]
must use init?(coder aDecoder: NSCoder)?

**Comment by ystrot** [comment]
Hi @tospery,

Could you please clarify your question?

**Comment by ClumsySmurf** [comment]
I believe he want's to initialize a MacawView without needing aDecoer reference. like init(svgString: String, frame: Frame?) or something that would return the UIView instead of decoding from xib/storyboard etc?.
