### ISSUE TITLE
Change SVG fill color

### ISSUE THREAD

**Issue by khoren93** [exyte/Macaw#66]
Hi, thanks for great lib :) I have a few questions.
Is it possible to change the SVG node fill color and can i get original size from node?
![fullsizerender](https://cloud.githubusercontent.com/assets/11523360/20144465/23b88b9e-a6b6-11e6-8bcb-73af1251dffd.jpg)

**Comment by ystrot** [comment]
Hey, Khoren. Thank you!

You may change the color, but you need to find a node to change. SVG parser returns you tree of nodes, so you need to traverse trough that tree and change parts you need. Probably you can do something like this (this function change every red shape to blue one):

```swift
private func replaceColors(node: Node) {
    if let group = node as? Group {
        for child in group.contents {
            replaceColors(node: child)
        }
    } else if let shape = node as? Shape {
        if let color = shape.fill as? Color {
            if (color.val == 0xff0000) {
                shape.fill = Color.blue
            }
        }
    }
}
```

**Comment by ystrot** [comment]
As for original size, unfortunately, we do not provide it yet. Probably, we'll implement this feature in future.

**Comment by khoren93** [comment]
Thank You :)
