### ISSUE TITLE
Add Swift Packages Support [SPM]

### ISSUE THREAD

**Issue by JaydenIrwin** [exyte/Macaw#664]

**Comment by wilwet** [comment]
Could you indicate when swift package support will be available. getting Macaw gives the following error.
Showing All Messages
Add Package
Showing All Messages
Fetching https://github.com/exyte/Macaw
Showing All Messages
: https://github.com/exyte/Macaw has no Package.swift manifest for version 0.9.5

**Comment by amarunko** [comment]
Hi, as I remember, there is a pull request on this feature, let me check

**Comment by amarunko** [comment]
Available now in the master branch
