### ISSUE TITLE
Carthage update not working for Xcode 11.4

### ISSUE THREAD

**Issue by SSenocico** [exyte/Macaw#675]
<img width="1061" alt="Screenshot 2020-03-25 at 17 22 00" src="https://user-images.githubusercontent.com/60232541/77553227-3547e580-6ebd-11ea-8a12-c3641c679cea.png">

I clone the project. It doesn't compile due to some errors.

**Comment by thomasmfinalcad** [comment]
Hi, I've the same problem with 0.9.5 ...

**Comment by ThomasLeblond** [comment]
Hello,

The PR for Swift 5.2 update was merged 4 days ago (https://github.com/exyte/Macaw/pull/669), can please tag the commit and create the version?

This is only take few minutes for you and it will be really useful for us :)

**Comment by ystrot** [comment]
Hi Thomas,

Master version is not stable yet, we'll create a new version once several issues will be fixed (hope it will happen soon). For now, please feel free to create, tag and use your fork of the master branch if it works fine for you.

**Comment by ThomasLeblond** [comment]
Hello @ystrot,

I can't because i use Macaw not directly but by another dependency.

And to be honest and know why this is merged in `master` if it's not stable 🤔.

**Comment by ystrot** [comment]
Just released 0.9.6 with Swift 5.2 support.
