### ISSUE TITLE
Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2 compiler

### ISSUE THREAD

**Issue by Usman4Github** [exyte/Macaw#677]
Please prepare a build with new xcode 11.4

**Comment by RandallWang** [comment]
I find this in [xcode_11_4_release_notes](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_4_release_notes)

> A method override can no longer have a generic signature with requirements not imposed by the base method. For example, the below code produces an error. (23626260) (FB5382462)
> 
> protocol P {}
>       
> class Base {
>     func foo<T>(arg: T) {}
> }
>       
> class Derived: Base {
>     // generates an error because of the added requirement
>     override func foo<T: P>(arg: T) {}
> }

**Comment by ystrot** [comment]
Just released 0.9.6 with Swift 5.2 support.
