### ISSUE TITLE
Latest pod version (0.9.5) not updated to Swift 5.2

### ISSUE THREAD

**Issue by bauermusic** [exyte/Macaw#678]
It looks like Swift 5.2 updates were merged into master, but the latest version tag is 0.9.5 and is not updated.
Swift 5.2 has some breaking changes, so currently, cannot compile library with latest pod.
(currently, we're fetching directly from master).

**Comment by FiendishCorp** [comment]
Any ideas when this will be fixed? Thanks for all your hard work on Macaw!

**Comment by ystrot** [comment]
Just released 0.9.6 with Swift 5.2 support.
