### ISSUE TITLE
Version 0.9.5 doesn't build in Xcode 11.4

### ISSUE THREAD

**Issue by Argent** [exyte/Macaw#679]
- Create an empty new project
- Run `pod init`
- Add `pod "Macaw", "0.9.5"` to podfile
- Run `pod install`
- Try to build

=> Project doesnt compile with errors like these:
```
Overridden method 'equals' has generic signature <T where T : Gradient> which is incompatible with base method's generic signature <T where T : Fill>; expected generic signature to be <T where T : Fill>
```

![image](https://user-images.githubusercontent.com/717301/78153524-713df600-743b-11ea-9334-486938ad92ba.png)

**Comment by ystrot** [comment]
Hi Benjamin,

This issue already fixed in the master branch.
