### ISSUE TITLE
It is possible to convert UIBezierPath to Locus (form for shape)?

### ISSUE THREAD

**Issue by ernichechelski** [exyte/Macaw#688]
Sorry, but I didn't manage to find a way how to create very custom shapes using UIBezierPath (MBezierPath). :(

**Comment by f3dm76** [comment]
@ernichechelski Unfortunately that's true - there isn't one. There is a `Path` `Locus` which looks like what you need, but it can't be created directly from `UIBezierPath`. We've added it to our plans, but it's quite a bit of work, and will take a while. So in the meantime you might consider creating a PR adding this functionality.

**Comment by f3dm76** [comment]
Hey there @ernichechelski , we added CGPath.toMacaw(). You are most welcome to check out Macaw master branch. Have a great day!

**Comment by ernichechelski** [comment]
This message made my day! Thank you very much! I must say that this library makes implementing charts very productive and satisfying. Great work! 😄
