### ISSUE TITLE
Unexpected animation when changing Shape's fill color

### ISSUE THREAD

**Issue by AntonPoltoratskyi** [exyte/Macaw#692]
### Precondition
- I have the following code to change node's fill color by tap on it:

```swift
guard let node = svgView.node.nodeBy(tag: nodeId) as? Shape else {
    return
}
node.onTap { [weak self] _ in
    guard let self = self, let node = self.svgView.node.nodeBy(tag: nodeId) as? Shape else {
        return
    }
    let color = node.fill != self.selectedColor ? self.selectedColor : self.normalColor
    node.fillVar.animate(to: color, during: 0.3)
}
```

### Problem
- Node is scaling and translating as you could see at the following video:

<img src="https://user-images.githubusercontent.com/10827392/83413910-46fdba00-a425-11ea-9892-78c9c407c305.gif" width="250" />

### Demo project
- Please download this demo project with reproduced issue:
[SVGDemo.zip](https://github.com/exyte/Macaw/files/4711534/SVGDemo.zip)
- Do you have any idea how to resolve this issue? Thanks in advance!

**Comment by f3dm76** [comment]
Hello @AntonPoltoratskyi , thank you very much for your report, and a working example. Just wanted to let you know we started working on this issue, and will let you know one it's fixed. Have a great day!

**Comment by f3dm76** [comment]
Greetings @AntonPoltoratskyi ! Glad to let you know the issue is resolved, the fix will be included in future release, but for now please kindly check out the master Macaw branch. Could I also ask you a favour - may I please use your svg file (and basically the idea to highlight pieces on tap) to add a new example to Macaw?

**Comment by AntonPoltoratskyi** [comment]
Thanks a lot! Sure, you can use it - it is downloaded from open source https://www.amcharts.com/svg-maps/?map=argentina. Original idea is from this tutorial https://medium.com/@fede_nieto/interactive-svg-images-in-swift-with-macaw-1b0d7875511f but color was updated without animation there.
