### ISSUE TITLE
ITMS-90809: Deprecated API Usage for UIWebView

### ISSUE THREAD

**Issue by seungha-kim** [exyte/Macaw#710]
Hi everyone. First, very happy to use this great library. Thank you all!

I received deprecation warning from Apple recently:

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs starting from December 2020 . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

So I ran grep to find what parts are using UIWebView

```
$ grep -srl UIWebView *
Carthage/Checkouts/Macaw/Carthage/Build/iOS/Macaw.framework.dSYM/Contents/Resources/DWARF/Macaw
Carthage/Build/iOS/Macaw.framework.dSYM/Contents/Resources/DWARF/Macaw
```

It seems the `DWARF/Macaw` file contains just debugging symbols including UIKit, but I want to make sure that Macaw does not have any parts using UIWebView.

Thanks in advance!

**Comment by amarunko** [comment]
Hi, @seungha-kim , thank you! No, Macaw library doesn't use any UIWebView related classes, double checked

**Comment by seungha-kim** [comment]
Thank you for reply! 👍
