### ISSUE TITLE
Version 0.96 is missing a Package.swift file

### ISSUE THREAD

**Issue by michaelosity** [exyte/Macaw#711]
I'm not sure if this is an oversight or requires some type of code changes, but the Package.swift file is missing from the 0.96 release. It appears that the master branch has this file, but not the latest release.

**Comment by adamjcampbell** [comment]
@ystrot thanks for all your work on Macaw. Do you think it would be possible to get an `0.9.7` release to resolve this? I'm trying to create a framework that has Macaw as a dependency, however it's impossible to get SPM and Cocoapods pointing to the same version of Macaw without the use of forks at the moment.

**Comment by ystrot** [comment]
Hi @adamjcampbell

Yes, we'll release it in the nearest days.

**Comment by ystrot** [comment]
Macaw 0.9.7 just released!

**Comment by adamjcampbell** [comment]
Thanks @ystrot!
