### ISSUE TITLE
Unable to change stroke color - wrong behaviour of `node.strokeVar` property

### ISSUE THREAD

**Issue by AntonPoltoratskyi** [exyte/Macaw#713]
## Precondition

I have circle shape in my simple SVG file. 
```XML
<svg width="100px" height="100px" viewBox="0 0 100 100" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <circle id="circle" stroke="#2C2C2C" stroke-width="4" fill="#FF0000" fill-rule="nonzero" cx="40" cy="40" r="20"></circle>
    </g>
</svg>
```

That's all xml code that we need to reproduce the issue.

This circle is rendering like on this screenshot - circle with red fill color and black stroke color:
<img width="217" alt="Screenshot 2020-07-08 at 23 17 35" src="https://user-images.githubusercontent.com/10827392/86966572-10c50000-c172-11ea-8072-b8af12b8946e.png">

## Intention

I need to update stroke color, for instance from black to green. So I added the following code into my view controller:

```swift
import UIKit
import Macaw

final class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        
        let svgView = SVGView()
        svgView.contentMode = .scaleAspectFit
        svgView.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(svgView)
        
        NSLayoutConstraint.activate([
            view.topAnchor.constraint(equalTo: svgView.topAnchor),
            view.leadingAnchor.constraint(equalTo: svgView.leadingAnchor),
            view.trailingAnchor.constraint(equalTo: svgView.trailingAnchor),
            view.bottomAnchor.constraint(equalTo: svgView.bottomAnchor)
        ])
        svgView.fileName = "Circle"
        
        svgView.node.nodeBy(tag: "circle")?.onTap { event in
            guard let node = event.node as? Shape else {
                return
            }
            // `strokeVar` changes fill color, but not stroke color. So these 2 lines of code have the same effect.
            node.strokeVar.animate(to: Color.green, during: 0.3)
//            node.fillVar.animate(to: Color.green, during: 0.3)
        }
    }
}
```

Key line is:
```swift
node.strokeVar.animate(to: Color.green, during: 0.3)
```

## Expected Result

We expect the following result when user taps on circle:
<img width="216" alt="Screenshot 2020-07-08 at 23 15 44" src="https://user-images.githubusercontent.com/10827392/86967148-ed4e8500-c172-11ea-9a62-f0bbeffcd12e.png">

But result is different:
<img width="210" alt="Screenshot 2020-07-08 at 23 16 49" src="https://user-images.githubusercontent.com/10827392/86967229-08b99000-c173-11ea-8787-478ab53d3c6a.png">

So, `strokeVar`'s behaviour is the same like `fillVar`'s which looks incorrect.

You could see the behaviour on this video:
<img src="https://user-images.githubusercontent.com/10827392/86967389-3f8fa600-c173-11ea-9ffe-12954c78a4ca.gif" width="250" />

## Demo project
- I reproduced the issue in this demo project: [StrokeIssue.zip](https://github.com/exyte/Macaw/files/4893145/StrokeIssue.zip)
- Do you have any idea how it can be fixed? Thanks in advance!

**Comment by ystrot** [comment]
It's definitely a bug that you can call this method on the `Stroke` and it will be fixed. However you can just call the correct one to animate stroke of the shape:
```Swift
node.strokeVar.animate(to: Stroke(fill: Color.green, width: 4), during: 0.3)
```

**Comment by AntonPoltoratskyi** [comment]
I tried and stroke color is changed, thanks! But is there any way to combine stoke and fill animation simultaneously?
like: 
```swift
node.fillVar.animate(to: Color.blue, during: 0.3)
node.strokeVar.animate(to: Stroke(fill: Color.green, width: 4), during: 0.3)
```

Current result has undefined behaviour:

<img src="https://user-images.githubusercontent.com/10827392/87042242-1404ce00-c1fc-11ea-8021-3256471f0ad4.gif" width="250" />

Fill color is not applying correctly. Ideally fill and stroke animation looks independent, so they shouldn't affect each other.

**Comment by ystrot** [comment]
Yep, looks like a bug.
