### ISSUE TITLE
Xcode 12 compile error in ColorMatrix.swift

### ISSUE THREAD

**Issue by jminutaglio** [exyte/Macaw#719]
In Xcode 12 (Version 12.0 beta 3 (12A8169g)):

Error:
`The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions`

FIle:
`ColorMatrix.swift`

In:
`public convenience init(hueRotate: Double) {
        let c = cos(hueRotate)
        let s = sin(hueRotate)
        let m1 = [0.213, 0.715, 0.072,
                  0.213, 0.715, 0.072,
                  0.213, 0.715, 0.072]
        let m2 = [0.787, -0.715, -0.072,
                  -0.213, 0.285, -0.072,
                  -0.213, -0.715, 0.928]
        let m3 = [-0.213, -0.715, 0.928,
                  0.143, 0.140, -0.283,
                  -0.787, 0.715, 0.072]
        let a = { i in
            m1[i] + c * m2[i] + s * m3[i]
        }
        self.init(values: [a(0), a(1), a(2), 0, 0,
                           a(3), a(4), a(5), 0, 0,
                           a(6), a(7), a(8), 0, 0,
                           0, 0, 0, 1, 0])
    }`

Complier error is in the "let a =...." , line 60 in the file.

**Comment by ystrot** [comment]
This issue already fixed in the master branch.
