### ISSUE TITLE
Load an svg file and render it onto a UIView

### ISSUE THREAD

**Issue by karimfikani** [exyte/Macaw#72]
Is it possible with Macaw to load an svg file and render it onto a UIView? Something similar to https://github.com/pocketsvg/PocketSVG

**Comment by shipinev** [comment]
Hi @karimfikani!

With latest master updates you can render SVG by using [SVGView](https://github.com/exyte/Macaw/wiki/Render-SVG-file).
You need to specify that with your pod declaration:
```text
pod 'Macaw', :git => 'https://github.com/exyte/Macaw.git'
```

If you have any further questions, please don't hesitate to ask.

**Comment by karimfikani** [comment]
Thank you @shipinev for your reply. Actually I meant if svg files can be loaded dynamically into a uiview through code and not by dragging and dropping it to a uiview. If yes, can you provide me with a code sample that does that? I looked at the examples repository that you have and couldn't find anything related to loading from files. Thanks.

**Comment by shipinev** [comment]
Yep, of course. You need to create programatically  SVGView with needed frame and set fileName attribute which automatically calls rendering proccess of your SVG file:
```swift
let svgView = SVGView(frame: CGRect(x: 0, y: 0, width: 200, height: 200))
svgView.fileName = "svgFileName"```

**Comment by karimfikani** [comment]
So I loaded the following svg file 
[rabbit.svg.zip](https://github.com/exyte/Macaw/files/635613/rabbit.svg.zip)

and got the following:

![simulator screen shot dec 6 2016 7 14 45 pm](https://cloud.githubusercontent.com/assets/2486075/20953439/894e2a26-bbe8-11e6-9ec4-892f9da0789e.png)

**Comment by shipinev** [comment]
I'm fixed this issue, please try to render your SVG file now.

![simulator screen shot 7 dec 2016 12 58 28](https://cloud.githubusercontent.com/assets/553051/20956505/f3bb34be-bc7c-11e6-8396-93dd5fdc0810.png)

**Comment by karimfikani** [comment]
it works thanks!
