### ISSUE TITLE
How can I scale the SVGView?

### ISSUE THREAD

**Issue by karimfikani** [exyte/Macaw#75]
I'm using the following code to scale up the svg file:

`class SVGExampleView: MacawView {
    
    required init?(coder aDecoder: NSCoder) {
        super.init(node: SVGParser.parse(path: "Animals/duck50x50")!, coder: aDecoder)
        
        self.transform = CGAffineTransform(scaleX: 5, y: 5)
    }
    
}`

But I get a pixelated image

![simulator screen shot dec 7 2016 7 44 20 pm](https://cloud.githubusercontent.com/assets/2486075/20996864/96bc98f0-bcb5-11e6-8e71-da6b6bb037b1.png)

How can I scale properly because form what I know svg should scale without loosing any quality.

**Comment by zapletnev** [comment]
@karimfikani thanks for using Macaw! To scale without losing quality you have to use Macaw transformations:
```
class SVGExampleView: MacawView {
	required init?(coder aDecoder: NSCoder) {
        	let duck = SVGParser.parse(path: "duck")!
        	duck.place = .scale(sx: 2, sy: 2)
		super.init(node: duck, coder: aDecoder)
	}
}
```
For more info you can check [Transform section](https://github.com/exyte/Macaw/wiki/Getting-started#transform) in Getting started guide.

**Comment by zapletnev** [comment]
@karimfikani please let me know if any questions remain. I will close this issue for now.

**Comment by kmalkic** [comment]
Scaling a Shape doesn't seem to change the bounds of it. is there a way?

**Comment by ystrot** [comment]
Hi Kevin,

`Shape.bounds` is not affected by a node's place. If you want to apply transformation, if you may use following code:
```Swift
let bounds = shape.bounds!.applying(shape.place)
```
P.S. it's better to create a new issue for a question, otherwise it might be missed.
