### ISSUE TITLE
[QUESTION] Is it possible to have limits for zooming on SVGView?

### ISSUE THREAD

**Issue by berkdilek** [exyte/Macaw#755]
Hi,

I have an SVGView that works as expected. Renders perfectly, nodes created as expected.

When I enable zoom with `svgView.zoom.enable()`, it is possible to zoom in and zoom out. I've been looking for a way to set a limit to how much a user can zoom.

For example, I don't want users to zoom out more than SVGView's original size. Similarly, zooming in extremely does break the user experience. 

Is there a way to set zoom limits for SVGView?

Thanks

**Comment by ystrot** [comment]
Hi @berkdilek,

Currently it's not supported, but good idea to add this.
