### ISSUE TITLE
Can we convert NSImage to SVG? or PNG to SVG? MACOSx Swift 5.

### ISSUE THREAD

**Issue by YogeshPateliOS** [exyte/Macaw#760]
Actually, I want to convert NSImage to SVG means Bitmap to vector in swift 5. 
Please give me your suggestion. How can I achieve this. Thank You!

**Comment by ystrot** [comment]
No, there is no such a functionality in Macaw, probably you're looking something like that: https://github.com/pcolton/potrace

**Comment by YogeshPateliOS** [comment]
Yes, I did this using Potrace Libary, and see your comment. By the way thanks for your reply and suggestion :-)
