### ISSUE TITLE
Swift Compiler Error on Xcode 13 - Macaw doesn't compile

### ISSUE THREAD

**Issue by Sileo1024** [exyte/Macaw#774]
#### Issue
The pod doesn't compile on Xcode 13. The compiler returns 88 issues within Macaw.

### Stack
- installed with CocoaPods (1.11.2)
- Xcode Version 13.0 (13A233)
- macOS Big Sur 11.6
- minimum target: iOS 13.0

### What I already tried:
- Running both on simulators, and devices.
- Cleaning Derrived Data
- Cleaning Pods Cache
- Reinstalling Pods
- Clean builds
- Restarting Xcode, and the whole system
- Deleting workspace and generating it from scratch

So far I deduced that the issue is most likely linked to the compiler change that Swift 5.5 shipped with Xcode 13.

<img width="1432" alt="Screenshot 2021-10-07 at 15 54 12" src="https://user-images.githubusercontent.com/4948552/136398502-ad52713a-9096-4e8c-b2d5-a5430a08caaf.png">

**Comment by f3dm76** [comment]
Hey @Sileo1024, we launched Macaw on xcode 13 and it compiles ok except for SWXMLHash library - for which we just released a fix in version 0.9.8, please check it out. Do you get all these mistakes just trying to compile Macaw? Have a nice day

**Comment by Sileo1024** [comment]
@f3dm76 I was using 0.9.8 version. It seems that you need to do a clean install of Xcode 13, and clean install of cocoapods, and this goes away. Thank you for your support. I'm closing this issue since I got this solved.
