### ISSUE TITLE
Why some SVG does not support contentMode ?

### ISSUE THREAD

**Issue by nverinaud** [exyte/Macaw#86]
I have a shape which does not render correctly, ie. does not scale and move respecting the content mode.

Here is the code I use:
```swift
let node = SVGParser.parse(bundle: Bundle.main, path: "Shape", ofType: "svg")!
let svgView = SVGView(node: node, frame: CGRect(x: 0, y: 0, width: 320, height: 480))

svgView.contentMode = .scaleAspectFit
svgView.backgroundColor = .white
```

I would be happy to help, just point me to the right direction so that I can investigate. 😉

[Shape.svg.zip](https://github.com/exyte/Macaw/files/698159/Shape.svg.zip)

![rendering-ios](https://cloud.githubusercontent.com/assets/824162/21838998/b22f6e38-d7d5-11e6-9482-bce2ba197589.png)

**Comment by shipinev** [comment]
Hi, @nverinaud!

Thanks for your report! Previously users were allowed to use SVGView via Interface Builder only. Now, this issue is fixed, and you can instantiate SVGView programmatically.

You can install Macaw directly from GitHub repository to get the latest changes:
```text
pod 'Macaw', :git => 'https://github.com/exyte/Macaw.git'
```
